charts/llms/Chart.yaml, charts/llms/templates/deployment.yaml, charts/llms/templates/ingress.yaml, charts/llms/templates/service.yaml, charts/llms/values.yaml, llms/Dockerfile, llms/docker-compose.yml
=> feat: llm controller service helm chart & dockerfile

examples/dashscope/main.go, pkg/llms/dashscope/api.go, pkg/llms/dashscope/params.go, pkg/llms/dashscope/response.go
example program output for llama2:
```
I1010 11:45:18.289582   21380 main.go:52]
Chat with llama2-7b-chat-v2
I1010 11:45:31.952627   21380 main.go:57] Response:
{"output":{"choices":[{"finish_reason":"stop","message":{"role":"assistant","content":" Great, I'm glad you think so! To change the image of a deployment in Kubernetes, you can use the `kubectl` command-line tool. Here are the steps:\n\n1. Identify the name of the deployment you want to change the image for. You can use the `kubectl get deployments` command to list all the deployments in your cluster and their current status.\n2. Use the `kubectl replace` command to replace the current image of the deployment with a new one. For example:\n```\nkubectl replace deployment \u003cdeployment-name\u003e --image=new-image\n```\nReplace …
```
=> feat: add llama2 in dashscope as llm

README.md, examples/dashscope/main.go, pkg/llms/dashscope/api.go, pkg/llms/dashscope/embedding.go, pkg/llms/dashscope/http_client.go, pkg/llms/dashscope/response.go, pkg/llms/dashscope/sse_client.go
For #101 
full output 
[output.txt](https://github.com/kubeagi/arcadia/files/12855733/output.txt)
for embedding:
=> feat: add text-embedding in dashscope

README.md, arctl/README.md, arctl/load.go, go.mod, go.sum
Changelogs:
- able to load multiple files/directories
- Use github.com/bjwswang/chroma-go which removes annoying `fmt.println`
=> feat: able to load multiple files into vector store with arctl

arctl/README.md, arctl/chat.go, arctl/dataset.go, pkg/embeddings/zhipuai/zhipuai.go
=> feat: able to configure text splitter in local dataset management

.github/workflows/example_test.yaml, Makefile, config/default/kustomization.yaml, config/rbac/role.yaml, config/samples/arcadia_v1alpha1_datasource.yaml, config/samples/example-test.sh, controllers/datasource_controller.go, tests/kind-config.yaml
=> feat: add example for CRD Datasource test

controllers/datasource_controller.go, pkg/datasource/datasource.go
=> feat: check datasource bucket and object

charts/arcadia/Chart.yaml, charts/arcadia/charts/minio/templates/post-job.yaml, charts/arcadia/templates/post-oss.yaml, controllers/datasource_controller.go, pkg/datasource/datasource.go
=> fix: datasource check bugs

go.mod, go.sum, graphql-server/go-server/README.md, graphql-server/go-server/graph/datasource.resolvers.go, graphql-server/go-server/graph/resolver.go, graphql-server/go-server/main.go, graphql-server/go-server/pkg/auth/auth.go, graphql-server/go-server/pkg/client/client.go, graphql-server/go-server/pkg/datasource/datasource.go, graphql-server/go-server/pkg/oidc/oidc.go
/kind feature
feat: support oidc auth.
Fixes # https://github.com/kubeagi/arcadia/issues/152
=> feat: support oidc auth

charts/arcadia/Chart.lock, charts/arcadia/Chart.yaml, charts/arcadia/crds/arcadia.kubeagi.k8s.com.cn_datasets.yaml, charts/arcadia/crds/arcadia.kubeagi.k8s.com.cn_versioneddatasets.yaml, charts/arcadia/templates/config.yaml, charts/arcadia/templates/deployment.yaml, charts/arcadia/templates/rbac.yaml, config/rbac/role.yaml, controllers/datasource_controller.go, go.mod, graphql-server/go-server/graph/resolver.go, main.go, pkg/config/config.go, pkg/config/config_type.go, pkg/datasource/datasource.go
=> feat: init default controller config

charts/arcadia/Chart.lock, charts/arcadia/Chart.yaml, charts/arcadia/charts/fastchat/Chart.yaml, charts/arcadia/charts/fastchat/templates/service.yaml, charts/arcadia/charts/fastchat/values.yaml
=> chore: change default image and service name for fastchat

charts/arcadia/Chart.yaml, charts/arcadia/values.yaml
=> chore: expose ingress settings for fastchat in arcadia

graphql-server/go-server/graph/datasource.graphqls, graphql-server/go-server/graph/datasource.resolvers.go, graphql-server/go-server/graph/generated.go, graphql-server/go-server/graph/model/models_gen.go, graphql-server/go-server/pkg/datasource/datasource.go
=> feat: update datasource api

graphql-server/go-server/main.go, graphql-server/go-server/pkg/client/client.go
/kind feature
feat: add parameter whether to enable oidc
Fixes #
=> feat: add parameter whether to enable oidc

Dockerfile
/kind bug
fix: graphql-server can't run
Fixes #
=> fix: graphql-server can't run

graphql-server/go-server/main.go
/kind feature
feat: support api prefix for graphql playground
Fixes #
=> feat: support api prefix for graphql playground

graphql-server/bff-sdk/.fatherrc.ts, graphql-server/bff-sdk/.gitignore, graphql-server/bff-sdk/.npmrc, graphql-server/bff-sdk/README.md, graphql-server/bff-sdk/codegen-gql.mjs, graphql-server/bff-sdk/codegen.yml, graphql-server/bff-sdk/package.json, graphql-server/bff-sdk/pnpm-lock.yaml, graphql-server/bff-sdk/src/errors/handler.ts, graphql-server/bff-sdk/src/errors/index.ts, graphql-server/bff-sdk/src/errors/modal.ts, graphql-server/bff-sdk/src/errors/notification.ts, graphql-server/bff-sdk/src/index.ts, graphql-server/bff-sdk/src/sdk.ts, graphql-server/bff-sdk/src/useSWR.ts, graphql-server/bff-sdk/tsconfig.json, graphql-server/go-server/graph/datasource.gql
/kind feature
The front-end can use this SDK to call the API of the arcadia server
Fixes #
=> feat: add SDK to call the API

charts/arcadia/Chart.lock, charts/arcadia/Chart.yaml, charts/arcadia/charts/minio/Chart.yaml, charts/arcadia/charts/minio/values.yaml
=> chore: increase default proxy-body-size for nginx ingress in minio

charts/arcadia/Chart.yaml, charts/arcadia/templates/portal.yaml, charts/arcadia/values.yaml
=> feat: deploy graphql-server

charts/arcadia/Chart.yaml
=> chore: bump arcadia chart version

charts/llm-worker/.helmignore, charts/llm-worker/Chart.yaml, charts/llm-worker/README.md, charts/llm-worker/templates/NOTES.txt, charts/llm-worker/templates/_helpers.tpl, charts/llm-worker/templates/deployment.yaml, charts/llm-worker/templates/ingress.yaml, charts/llm-worker/templates/pvc.yaml, charts/llm-worker/templates/service.yaml, charts/llm-worker/values.yaml, llms/Dockerfile.worker
=> [WIP]feat: add model worker helm chart

graphql-server/go-server/graph/datasource.graphqls, graphql-server/go-server/graph/datasource.resolvers.go, graphql-server/go-server/graph/generated.go, graphql-server/go-server/graph/model/models_gen.go, graphql-server/go-server/pkg/datasource/datasource.go
=> feat: graphql-server supplement

arctl/datasource.go, arctl/main.go
=> fix: golangci-lint errors

charts/arcadia/Chart.yaml, charts/arcadia/templates/portal.yaml, charts/arcadia/values.yaml
/kind bug
chore: optimize graphql-server chart
Fixes #
=> chore: optimize graphql-server chart

arctl/datasource.go, graphql-server/bff-sdk/package.json, graphql-server/bff-sdk/src/sdk.ts, graphql-server/go-server/graph/datasource.gql, graphql-server/go-server/graph/datasource.graphqls, graphql-server/go-server/graph/datasource.resolvers.go, graphql-server/go-server/graph/generated.go, graphql-server/go-server/graph/model/models_gen.go, graphql-server/go-server/pkg/datasource/datasource.go
/kind feature
list datasources
Fixes #
=> feat: list datasources

data-process/data_manipulation/common/config.py, data-process/data_manipulation/file_handle/csv_handle.py, data-process/data_manipulation/transform/text/QA_transform.py, data-process/requirements.txt
feat:generate Q&A pairs from text by zhipuai
=> feat:generate Q&A pairs from text by zhipuai

Makefile, charts/arcadia/Chart.yaml, charts/arcadia/templates/rbac.yaml, pkg/scheduler/job.go
=> feat: add make prepare-push

charts/arcadia/Chart.yaml
=> fix: bump arcadia chart version

kubeagi.yaml
=> chore: typos in kubeagi.yaml

.github/workflows/release.yaml, README.md, pkg/scheduler/scheduler.go
=> fix: chart release workflow and README

api/v1alpha1/condition.go, api/v1alpha1/versioneddataset.go, config/rbac/role.yaml, controllers/dataset_controller.go, controllers/versioneddataset_controller.go, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/rbac.yaml, pkg/scheduler/executor.go, pkg/scheduler/scheduler.go
/kind bug
fix: rename bucket name, and add missing permission
Fixes #
```yaml
version: v1
status:
conditions:
- lastTransitionTime: "2023-11-18T10:48:22Z"
message: def/server.key sync failed, The specified key does not exist.
reason: FileSyncFailed
status: "False"
type: Ready
datasourceFiles:
- datasourceName: for-dataset
datasourceNamespace: arcadia
status:
- errMessage: The specified key does not exist.
path: def/server.key
phase: Failed
- lastUpdateTime: "2023-11-18T10:48:22Z"
path: test/ca.crt
phase: Succeeded
- lastUpdateTime: "2023-11-18T10:48:22Z"
path: test/ca.key
phase: Succeeded
```
=> fix: rename bucket name, and add missing permission

.github/workflows/release.yaml, Makefile, tests/example-test.sh
=> fix: some github action failed due to refactor

graphql-server/bff-sdk/codegen.yml, graphql-server/bff-sdk/package.json, graphql-server/bff-sdk/src/index.ts, graphql-server/bff-sdk/src/sdk.ts, graphql-server/go-server/graph/schema/datasource.gql, graphql-server/go-server/graph/schema/model.gql
/kind feature
add model.gql
Fixes #
=> feat: add Model.gql

gqlgen.yaml, graphql-server/go-server/graph/generated/generated.go, graphql-server/go-server/graph/generated/models_gen.go, graphql-server/go-server/graph/impl/datasource.resolvers.go, graphql-server/go-server/graph/schema/datasource.graphqls, graphql-server/go-server/pkg/datasource/datasource.go, pkg/arctl/datasource.go
=> feat: add datasource comments and update fields

deploy/charts/llm-worker/Chart.yaml, deploy/charts/llm-worker/README.md, deploy/charts/llm-worker/templates/deployment.yaml, deploy/charts/llm-worker/values.yaml, pkg/worker/runner.go, pkg/worker/worker.go
=> feat: worker support VLLM

go.mod, go.sum, graphql-server/go-server/main.go, graphql-server/go-server/pkg/minio/client.go, graphql-server/go-server/pkg/minio/model/file_chunk.go, graphql-server/go-server/pkg/minio/service.go, pkg/config/config.go, pkg/config/config_type.go
/kind feature
breakpoint upload via MinIO
Fixes #
=> feat: breakpoint upload via MinIO

api/v1alpha1/versioneddataset.go, deploy/charts/arcadia/crds/arcadia.kubeagi.k8s.com.cn_workers.yaml, graphql-server/go-server/graph/generated/generated.go, graphql-server/go-server/graph/generated/models_gen.go, graphql-server/go-server/graph/impl/dataset.resolvers.go, graphql-server/go-server/graph/impl/versioned_dataset.resolvers.go, graphql-server/go-server/graph/schema/versioned_dataset.graphqls, graphql-server/go-server/pkg/minio/client.go, graphql-server/go-server/pkg/minio/service.go, graphql-server/go-server/pkg/versioneddataset/versioned_dataset.go, pkg/config/config.go, pkg/utils/minioutils/minioutils.go
/kind feature
feat: versionedataset graphql api
Fixes #
=> feat: versionedataset graphql api

graphql-server/bff-sdk/package.json, graphql-server/bff-sdk/src/sdk.ts, graphql-server/go-server/graph/schema/dataset.gql, graphql-server/go-server/graph/schema/model.gql, graphql-server/go-server/graph/schema/versioned_dataset.gql
/kind feature
feat: add dataset.gql and versioned_dataset.gql
Fixes #
=> feat: add dataset.gql and versioned_dataset.gql

graphql-server/go-server/graph/impl/dataprocess.resolvers.go, graphql-server/go-server/main.go, graphql-server/go-server/pkg/dataprocessing/dataprocessing.go, graphql-server/go-server/pkg/dataset/dataset.go
=> feat: impl dataprocessing list api

graphql-server/go-server/graph/schema/embedder.gql, graphql-server/go-server/graph/schema/knowledgebase.gql
=> feat: add embedder and knowledgebase gql

.github/workflows/example_test.yaml, controllers/knowledgebase_controller.go, tests/example-test.sh
=> feat: support minio object tag for knowledgebase

data-processing/data_manipulation/db/data_process_task.py, data-processing/data_manipulation/file_handle/csv_handle.py, data-processing/data_manipulation/file_handle/pdf_handle.py, data-processing/data_manipulation/kube/client.py, data-processing/data_manipulation/kube/custom_resources.py, data-processing/data_manipulation/server.py, data-processing/data_manipulation/service/data_process_service.py, data-processing/data_manipulation/service/minio_store_process_service.py, data-processing/data_manipulation/transform/text/QA_transform.py, data-processing/data_manipulation/transform/text/clean_transform.py, data-processing/data_manipulation/utils/log_utils.py, data-processing/data_manipulation/utils/minio_utils.py, data-processing/data_manipulation/utils/pg_utils.py
=> feat: add kubeenv for data processing

.github/workflows/image_build.yml
=> chore: add data-process image build to workflow

graphql-server/go-server/graph/generated/generated.go, graphql-server/go-server/graph/generated/models_gen.go, graphql-server/go-server/graph/schema/versioned_dataset.graphqls, graphql-server/go-server/pkg/versioneddataset/versioned_dataset.go
/kind bug
chore: modify the file filter structure
Fixes #
=> chore: modify the file filter structure

deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/config.yaml, deploy/charts/arcadia/templates/vectorstore.yaml, deploy/charts/arcadia/values.yaml, graphql-server/go-server/graph/impl/knowledgebase.resolvers.go, graphql-server/go-server/graph/schema/knowledgebase.gql, pkg/config/config.go, pkg/config/config_type.go
=> fix: set default vectorstore

controllers/embedder_controller.go
=> [WIP]chore: fix embedder controller

go.mod, go.sum, graphql-server/go-server/pkg/minio/model/file_chunk.go, graphql-server/go-server/pkg/minio/service.go
chore: add bucket and bucket_paht query parameter
Fixes #
=> chore: add bucket and bucket_paht query parameter

graphql-server/go-server/graph/generated/generated.go, graphql-server/go-server/graph/generated/models_gen.go, graphql-server/go-server/graph/impl/dataset.resolvers.go, graphql-server/go-server/graph/schema/dataset.gql, graphql-server/go-server/graph/schema/dataset.graphqls, graphql-server/go-server/graph/schema/versioned_dataset.gql, graphql-server/go-server/graph/schema/versioned_dataset.graphqls, graphql-server/go-server/pkg/dataset/dataset.go, graphql-server/go-server/pkg/versioneddataset/versioned_dataset.go
fix: add version count and file count, update gql
Fixes #
=> fix: add version count and file count, update gql

deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/dataprocess.yaml, deploy/charts/arcadia/values.yaml
=> feat: add dataprocess helm chart

graphql-server/go-server/pkg/dataset/dataset.go, graphql-server/go-server/pkg/versioneddataset/versioned_dataset.go
fix: add version count and file count, update gql
Fixes #
=> fix: page panic

api/v1alpha1/versioneddataset.go, pkg/scheduler/executor.go
fix: supports synchronization of already uploaded data
=> fix: supports synchronization of already uploaded data

deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/portal.yaml, deploy/charts/arcadia/values.yaml, deploy/charts/llm-worker/values.yaml
=> fix: portal & minio env values

graphql-server/go-server/graph/generated/generated.go, graphql-server/go-server/graph/generated/models_gen.go, graphql-server/go-server/graph/impl/knowledgebase.resolvers.go, graphql-server/go-server/graph/schema/datasource.graphqls, graphql-server/go-server/graph/schema/knowledgebase.graphqls, graphql-server/go-server/pkg/datasource/datasource.go, graphql-server/go-server/pkg/knowledgebase/knowledgebase.go
=> fix: update knowledgebase to display filedetail.status

data-processing/data_manipulation/db/data_process_task.py, data-processing/data_manipulation/server.py, data-processing/data_manipulation/service/minio_store_process_service.py, data-processing/data_manipulation/transform/text/support_type.py, data-processing/data_manipulation/utils/pg_utils.py, data-processing/requirements.txt
=> fix:add PostgreSQL connection pool

graphql-server/go-server/graph/generated/generated.go, graphql-server/go-server/graph/generated/models_gen.go, graphql-server/go-server/graph/schema/knowledgebase.gql, graphql-server/go-server/graph/schema/knowledgebase.graphqls, graphql-server/go-server/pkg/knowledgebase/knowledgebase.go
=> fix: correctly display knowledgebase return status

config/rbac/role.yaml, config/samples/arcadia_v1alpha1_embedders.yaml, config/samples/arcadia_v1alpha1_llm.yaml, controllers/namespace_controller.go, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/rbac.yaml, main.go
/kind feature
chore: create and delete buckets based on namespace changes
Fixes #
=> feat: create and delete buckets based on namespace changes

config/samples/arcadia_v1alpha1_embedders.yaml, config/samples/arcadia_v1alpha1_llm.yaml, controllers/worker_controller.go
=> fix: ignore already exist error in worker reconcile

graphql-server/go-server/pkg/versioneddataset/versioned_dataset.go
=> fix: trim prefix from the versioneddataset file path

controllers/knowledgebase_controller.go
=> fix: use RecursiveCharacter to replace TokenSplitter to skip net req

controllers/embedder_controller.go, controllers/llm_controller.go, controllers/prompt_controller.go, pkg/llms/openai/api.go
=> feat: able to configure base url for openai kind of llms/embedders

data-processing/data_manipulation/common/config.py, data-processing/data_manipulation/db/data_process_task.py, data-processing/data_manipulation/file_handle/pdf_handle.py, data-processing/data_manipulation/kube/client.py, data-processing/data_manipulation/server.py, data-processing/data_manipulation/service/data_process_service.py, data-processing/data_manipulation/service/dataset_service.py, data-processing/data_manipulation/service/minio_store_process_service.py, data-processing/data_manipulation/transform/text/QA_transform.py, data-processing/data_manipulation/utils/date_time_utils.py, data-processing/data_manipulation/utils/minio_utils.py, data-processing/requirements.txt, graphql-server/go-server/graph/generated/generated.go, graphql-server/go-server/graph/generated/models_gen.go, graphql-server/go-server/graph/schema/dataprocessing.graphqls
fix: solving connectivity issues with MinIO
fix: resolving issues with text segmentation
feat: handle dataset status
=> feat:handle dataset status

gqlgen.yaml, graphql-server/go-server/graph/generated/generated.go, graphql-server/go-server/graph/generated/models_gen.go, graphql-server/go-server/graph/impl/dataprocessing.resolvers.go, graphql-server/go-server/graph/schema/dataprocessing.gql, graphql-server/go-server/graph/schema/dataprocessing.graphqls, graphql-server/go-server/pkg/dataprocessing/dataprocessing.go
feat:data processing details for graphql
=> feat:data processing details for graphql

controllers/knowledgebase_controller.go, controllers/namespace_controller.go
=> fix: use 1 Hour to replace 1 minutes for long time reconcile

graphql-server/go-server/main.go
=> fix: use gin for minio url

api/base/v1alpha1/model_types.go, config/crd/bases/arcadia.kubeagi.k8s.com.cn_models.yaml, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/crds/arcadia.kubeagi.k8s.com.cn_models.yaml, graphql-server/go-server/graph/generated/generated.go, graphql-server/go-server/graph/generated/models_gen.go, graphql-server/go-server/graph/impl/knowledgebase.resolvers.go, graphql-server/go-server/graph/impl/model.resolvers.go, graphql-server/go-server/graph/schema/datasource.gql, graphql-server/go-server/graph/schema/embedder.gql, graphql-server/go-server/graph/schema/entrypoint.graphqls, graphql-server/go-server/graph/schema/knowledgebase.gql, graphql-server/go-server/graph/schema/knowledgebase.graphqls, graphql-server/go-server/graph/schema/model.gql, graphql-server/go-server/graph/schema/model.graphqls, graphql-server/go-server/pkg/knowledgebase/knowledgebase.go, graphql-server/go-server/pkg/model/model.go
knowledgebase:
1，添加字段 id，creationTimestamp
2，创建知识库时，embedder只输入name
3，所有name和namespace均为小写
model:
1，添加字段 id，creationTimestamp，status
2，删除字段field
Fixes #
=> fix: modify knowledgebase and model field

api/base/v1alpha1/common.go, controllers/app-node/chain/llmchain_controller.go, controllers/app-node/prompt/prompt_controller.go, controllers/application_controller.go, controllers/datasource_controller.go, controllers/embedder_controller.go, controllers/knowledgebase_controller.go, controllers/model_controller.go, controllers/namespace_controller.go, controllers/vectorstore_controller.go, controllers/versioneddataset_controller.go, controllers/worker_controller.go, deploy/charts/arcadia/values.yaml, graphql-server/go-server/pkg/minio/client.go, main.go, pkg/config/config.go, pkg/config/config_type.go, pkg/datasource/datasource.go, pkg/scheduler/scheduler.go, pkg/streamlit/deployer.go, pkg/utils/namespace.go
1. Refine log
2. Avoid repeated event of embedder controller and some other event handling
3. Support to deploy streamlit as the data app for each namespace
=> Refine some code logic and add streamlkit data-app support

.github/workflows/graphql_sdk_generate.yml, Makefile, deploy/charts/arcadia/Chart.yaml
/kind feature
A new version of the graphql sdk is automatically generated when a pull request is merged and a file is modified in `graphql-server/go-server/graph/schema/`.
Fixes #
need add two secrets: TENX_NPM_TOKEN and NPM_TOKEN
`//dev-npm.tenxcloud.net/:_authToken="${{ secrets.TENX_NPM_TOKEN }}"`
`//registry.npmjs.org/:_authToken="${{ secrets.NPM_TOKEN }}"`
=> feat: add auto graphql sdk generator action

graphql-server/go-server/README.md, graphql-server/go-server/graph/generated/generated.go, graphql-server/go-server/graph/generated/models_gen.go, graphql-server/go-server/graph/impl/dataset.resolvers.go, graphql-server/go-server/graph/impl/datasource.resolvers.go, graphql-server/go-server/graph/impl/embedder.resolvers.go, graphql-server/go-server/graph/impl/knowledgebase.resolvers.go, graphql-server/go-server/graph/impl/model.resolvers.go, graphql-server/go-server/graph/impl/resolver.go, graphql-server/go-server/graph/impl/versioned_dataset.resolvers.go, graphql-server/go-server/graph/schema/dataset.gql, graphql-server/go-server/graph/schema/dataset.graphqls, graphql-server/go-server/graph/schema/datasource.gql, graphql-server/go-server/graph/schema/datasource.graphqls, graphql-server/go-server/graph/schema/embedder.gql, graphql-server/go-server/graph/schema/embedder.graphqls, graphql-server/go-server/graph/schema/entrypoint.graphqls, graphql-server/go-server/graph/schema/knowledgebase.gql, graphql-server/go-server/graph/schema/knowledgebase.graphqls, graphql-server/go-server/graph/schema/model.gql, graphql-server/go-server/graph/schema/model.graphqls, graphql-server/go-server/pkg/dataset/dataset.go
/kind cleanup
#325 is to huge, split it to 2 part: refactor(this pr) and new change(#325)
Fixes #
=> refactor some graphql-server go code

.github/workflows/graphql_sdk_generate.yml, graphql-server/go-server/graph/generated/generated.go, graphql-server/go-server/graph/generated/models_gen.go, graphql-server/go-server/graph/schema/dataprocessing.gql, graphql-server/go-server/graph/schema/dataprocessing.graphqls, graphql-server/go-server/pkg/chat/chat.go, graphql-server/go-server/pkg/datasource/datasource.go, graphql-server/go-server/service/chat.go, pkg/application/app_run.go, pkg/application/chain/llmchain.go, pkg/application/chain/retrievalqachain.go, pkg/application/chain/stream.go, pkg/llms/zhipuai/api.go, pkg/llms/zhipuai/langchainllm.go, pkg/llms/zhipuai/sse_client.go
/kind feature
need merge #325 first.
```bash
curl -XPOST http://127.0.0.1:8081/chat --data '{"query":"旷工最小计算单位为多少天？","response_mode":"streaming","conversion_id":"","app_name":"base-chat-with-knowledgebase", "app_namespace":"arcadia"}'
data:{"conversion_id":"708bf843-4958-4e1d-bf95-79d4190e692f","message_id":"","message":"旷","created_at":"2023-12-08T16:14:53.884221628+08:00"}
data:{"conversion_id":"708bf843-4958-4e1d-bf95-79d4190e692f","message_id":"","message":"工","created_at":"2023-12-08T16:14:53.884294724+08:00"}
data:{"conversion_id":"708bf843-4958-4e1d-bf95-79d4190e692f","message_id":"","message":"最小","created_at":"2023-12-08T16:14:53.884316254+08:00"}
data:{"conversion_id":"708bf843-4958-4e1d-bf95-79d4190e692f","message_id":"","message":"计算","created_at":"2023-12-08T16:14:53.884363911 …
```
=> feat: add chat sse support

graphql-server/go-server/graph/schema/model.gql
=> chore: invalid syntax in model.gql

graphql-server/go-server/pkg/utils/structured.go, graphql-server/go-server/pkg/utils/structured_test.go
=> fix: MapStr2Any will panic

README.md, api/base/v1alpha1/model_types.go, config/crd/bases/arcadia.kubeagi.k8s.com.cn_models.yaml, config/rbac/role.yaml, controllers/namespace_controller.go, deploy/charts/arcadia/crds/arcadia.kubeagi.k8s.com.cn_models.yaml, deploy/charts/arcadia/templates/rbac.yaml, examples/rbac/inquiry.go, pkg/arctl/dataset.go, pkg/llms/zhipuai/params.go
=> chore: fix goreportcard link and misspell reported by goreport && chore: correct namespace controller rbac 

api/base/v1alpha1/common.go, api/base/v1alpha1/worker.go, controllers/knowledgebase_controller.go, go.mod, go.sum, pkg/arctl/chat.go, pkg/arctl/dataset.go
=> feat: knowledgebase support local worker embedder

controllers/knowledgebase_controller.go
=> feat: remove knowledgebase should remove data in vectorstore

api/base/v1alpha1/common.go, api/base/v1alpha1/embedder_types.go, api/base/v1alpha1/llm_types.go, api/base/v1alpha1/worker.go, config/crd/bases/arcadia.kubeagi.k8s.com.cn_datasources.yaml, config/crd/bases/arcadia.kubeagi.k8s.com.cn_embedders.yaml, config/crd/bases/arcadia.kubeagi.k8s.com.cn_llms.yaml, config/crd/bases/arcadia.kubeagi.k8s.com.cn_vectorstores.yaml, config/crd/kustomization.yaml, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/crds/arcadia.kubeagi.k8s.com.cn_datasources.yaml, deploy/charts/arcadia/crds/arcadia.kubeagi.k8s.com.cn_embedders.yaml, deploy/charts/arcadia/crds/arcadia.kubeagi.k8s.com.cn_llms.yaml, deploy/charts/arcadia/crds/arcadia.kubeagi.k8s.com.cn_vectorstores.yaml, deploy/charts/arcadia/templates/config.yaml, deploy/charts/arcadia/templates/post-datasource.yaml, pkg/config/config_type.go, pkg/worker/loader.go, pkg/worker/runner.go
=> feat: add internal url for endpoint

controllers/knowledgebase_controller.go, deploy/charts/arcadia/values.yaml, docs/run-llm-app-using-streamlit.md, examples/app-ui-using-streamlit/README.md, pkg/streamlit/deployer.go
Fix issues and add doc about how to use streamlit
=> Fix issues and add doc about how to use streamlit

api/base/v1alpha1/worker.go, config/samples/arcadia_v1alpha1_worker_baichuan2-7b.yaml, config/samples/arcadia_v1alpha1_worker_bge-large-zh-v1.5.yaml, examples/chat_with_worker/main.go, pkg/worker/runner.go
=> feat: utlize worker's UID as the model registration name

Dockerfile, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/post-models.yaml, deploy/charts/arcadia/templates/resource_reader.yaml, graphql-server/go-server/config/config.go, graphql-server/go-server/graph/generated/generated.go, graphql-server/go-server/graph/generated/models_gen.go, graphql-server/go-server/graph/impl/model.resolvers.go, graphql-server/go-server/graph/schema/model.gql, graphql-server/go-server/graph/schema/model.graphqls, graphql-server/go-server/graph/schema/worker.gql, graphql-server/go-server/graph/schema/worker.graphqls, graphql-server/go-server/pkg/common/schema.go, graphql-server/go-server/pkg/embedder/embedder.go, graphql-server/go-server/pkg/model/model.go, graphql-server/go-server/pkg/worker/worker.go
=> feat: able to view system pre-configured models

go.mod, graphql-server/go-server/main.go, graphql-server/go-server/pkg/oidc/auth.go
/kind bug
fix: remove client-go oidc cache.
Fixes #
=> fix: remove client-go oidc cache

graphql-server/go-server/graph/schema/model.gql
=> fix: fix modle.gql

graphql-server/go-server/pkg/model/model.go
=> fix: use condnition.status as the model status

api/base/v1alpha1/worker.go, graphql-server/go-server/graph/generated/generated.go, graphql-server/go-server/graph/generated/models_gen.go, graphql-server/go-server/graph/schema/worker.graphqls, graphql-server/go-server/pkg/model/model.go, graphql-server/go-server/pkg/worker/worker.go
=> chore: use a more simplified reason Running instead of WorkingRunnig

.github/workflows/example_test.yaml, .github/workflows/graphql_sdk_generate.yml, .github/workflows/image_build.yml, .github/workflows/lint_test.yaml, .github/workflows/release.yaml, .github/workflows/tests.yml, Dockerfile, Makefile
=> chore: update github action && add docker go proxy auto config

graphql-server/go-server/pkg/model/model.go
=> fix: skip to fetch system models if the ns is system namespace

graphql-server/go-server/pkg/common/read_csv.go, graphql-server/go-server/pkg/common/read_csv_test.go, graphql-server/go-server/service/minio_server.go
/kind feature
feat: support for reading csv files with several rows
Fixes #
=> feat: support for reading csv files with several rows

api/base/v1alpha1/worker.go, graphql-server/go-server/graph/generated/generated.go, graphql-server/go-server/graph/generated/models_gen.go, graphql-server/go-server/graph/schema/worker.gql, graphql-server/go-server/graph/schema/worker.graphqls, graphql-server/go-server/pkg/worker/worker.go
=> feat: able to configure worker type when create and update

api/base/v1alpha1/knowledgebase.go, controllers/knowledgebase_controller.go
Fixes #321
has been test success on my win.
=> fix: knowledgebase should reconcile fileGroups updates

controllers/knowledgebase_controller.go
=> chore: use golang errors replace k8s.io/apimachinery/pkg/util/errors

pkg/datasource/oss.go
/kind bug
fix: delete model files when model got deleted
Fixes #359
=> fix: delete model files when model got deleted

graphql-server/go-server/pkg/common/read_csv.go, graphql-server/go-server/pkg/common/read_csv_test.go, graphql-server/go-server/service/minio_server.go
/kind bug
fix: return the total number of rows in csv file
Fixes #
=> fix: return the total number of rows in csv file

deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/config.yaml, graphql-server/go-server/graph/generated/generated.go, graphql-server/go-server/graph/generated/models_gen.go, graphql-server/go-server/graph/schema/worker.gql, graphql-server/go-server/graph/schema/worker.graphqls, graphql-server/go-server/pkg/worker/worker.go, pkg/config/config_type.go
/kind bug
fix: model add api field
Fixes #
=> fix: model add api field

api/base/v1alpha1/worker.go, controllers/worker_controller.go, pkg/worker/worker.go
=> fix: updatetimestamp refeshed unexpectedly

api/base/v1alpha1/embedder.go, api/base/v1alpha1/embedder_types.go, api/base/v1alpha1/llm.go, api/base/v1alpha1/worker.go, controllers/embedder_controller.go, examples/chat_with_document/handler.go, examples/rbac/inquiry.go, examples/rbac/main.go, graphql-server/go-server/graph/generated/generated.go, graphql-server/go-server/graph/generated/models_gen.go, graphql-server/go-server/graph/schema/embedder.gql, graphql-server/go-server/graph/schema/embedder.graphqls, graphql-server/go-server/graph/schema/llm.gql, graphql-server/go-server/graph/schema/llm.graphqls, graphql-server/go-server/pkg/common/common.go, graphql-server/go-server/pkg/embedder/embedder.go, graphql-server/go-server/pkg/llm/llm.go, graphql-server/go-server/pkg/worker/worker.go, pkg/arctl/chat.go, pkg/embeddings/embeddings.go, pkg/langchainwrap/embedder.go, pkg/llms/llms.go, pkg/llms/zhipuai/api.go, pkg/llms/zhipuai/params.go
=> feat: able to get model list provided by Embedder and LLM

graphql-server/go-server/graph/generated/generated.go, graphql-server/go-server/graph/generated/models_gen.go, graphql-server/go-server/graph/impl/dataprocessing.resolvers.go, graphql-server/go-server/graph/schema/dataprocessing.graphqls, graphql-server/go-server/pkg/dataprocessing/dataprocessing.go
=> feat: add llm_config in data process config

apiserver/pkg/common/common.go, apiserver/pkg/datasource/datasource.go, apiserver/pkg/embedder/embedder.go, apiserver/pkg/knowledgebase/knowledgebase.go, apiserver/pkg/llm/llm.go, apiserver/pkg/model/model.go, apiserver/pkg/versioneddataset/versioned_dataset.go, apiserver/pkg/worker/worker.go
/kind bug
fix: check if the resource is in deletion
Fixes #
=> fix: check if the resource is in deletion

api/base/v1alpha1/versioneddataset_types.go, config/crd/bases/arcadia.kubeagi.k8s.com.cn_versioneddatasets.yaml, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/crds/arcadia.kubeagi.k8s.com.cn_versioneddatasets.yaml
chore: add validation rules to the versioneddataset field
Fixes #
=> chore: add validation rules to the versioneddataset field

deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/config.yaml, deploy/charts/arcadia/values.yaml
=> refactor: optimize dataprocessing config

apiserver/examples/upload-download-file/main.go, apiserver/pkg/common/file_chunk.go, apiserver/service/minio_server.go, pkg/datasource/datasource.go, pkg/datasource/oss.go
/kind bug
fix: remove minio uploadid cache
Currently there exists a local cache of uploadid where certain chunks are not uploaded completely, causing the front-end to not merge properly when uploading multiple times.
Fixes #
=> fix: remove minio uploadid cache

apiserver/pkg/common/read_csv.go, apiserver/pkg/common/read_csv_test.go, apiserver/service/minio_server.go, pkg/cache/lru.go, pkg/cache/lru_test.go
chore: cache the total number of lines in the csv file
Fixes #
=> chore: cache the total number of lines in the csv file

deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/charts/chromadb/values.yaml, deploy/charts/arcadia/templates/post-datasource.yaml, deploy/charts/arcadia/templates/post-models.yaml, deploy/charts/arcadia/templates/post-vectorstore.yaml, deploy/charts/arcadia/values.yaml, deploy/gpu-operator/nvidia_gpu.yaml, tests/deploy-values.yaml
Fixes #
Changelogs:
1. use clusterip for chromadb by default and remove useless fields in chromadb
2. use `cosine` as default distanceFunc and avoid to configure this in values.yaml
3. remove model `m3e-base` as system model
4. add image override for gpu-operator installation with kubebb
=> fix: use ClusterIP for chromadb by default

apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/schema/dataprocessing.gql, apiserver/graph/schema/dataprocessing.graphqls
What type of PR is this?
/kind feat
What this PR does / why we need it
add parameters related to file processing progress in the detail for graphql.
add 'top_p,' 'temperature,' 'max_tokens,' and 'prompt_template' parameters during task processing.
Which issue(s) this PR fixes
Fixes #
=> feat:add parameters related to file processing progress in the detail

api/base/v1alpha1/condition.go, api/base/v1alpha1/worker.go, api/base/v1alpha1/worker_types.go, api/base/v1alpha1/zz_generated.deepcopy.go, apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/schema/worker.gql, apiserver/graph/schema/worker.graphqls, apiserver/pkg/worker/worker.go, config/crd/bases/arcadia.kubeagi.k8s.com.cn_workers.yaml, config/samples/arcadia_v1alpha1_worker_baichuan2-7b.yaml, config/samples/arcadia_v1alpha1_worker_bge-large-zh-v1.5.yaml, config/samples/arcadia_v1alpha1_worker_qwen-7b-chat.yaml, controllers/embedder_controller.go, controllers/llm_controller.go, controllers/worker_controller.go, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/crds/arcadia.kubeagi.k8s.com.cn_workers.yaml, pkg/worker/worker.go
/kind feat
Fixes #393 
1. Add a new condition reason `Offline` to worker
2. Add a new field `replicas`(0,1) which is same as `deployment.spec.replicas`
3. Watch `Pod` instead of `Deployment` due to replica changes won't change deployment status
4. Create LLM/Embedder at `BeforeStart` which means `llm/embedder`  will be created even worker is not ready.
=> feat: able to offline worker instead of remove

apiserver/pkg/chat/chat.go, apiserver/service/chat.go, apiserver/service/router.go, pkg/application/app_run.go, pkg/application/chain/common.go
Fix sse support issue for streaming mode
=> Fix sse support issue for streaming mode

deploy/charts/arcadia/templates/kubebb-menus.yaml
/kind deploy
update portal menus
Fixes #
=> chore(helm): update arcadia portal menus

apiserver/pkg/application/application.go, apiserver/pkg/auth/auth.go, apiserver/pkg/chat/chat.go, apiserver/pkg/chat/chat_type.go, apiserver/service/chat.go, apiserver/service/router.go, config/samples/arcadia_v1alpha1_knowledgebase.yaml, pkg/application/app_run.go, pkg/application/chain/llmchain.go, pkg/application/chain/retrievalqachain.go, pkg/application/retriever/knowledgebaseretriever.go, tests/example-test.sh
/kind feature
more chat api, including answer knowledgebase reference, message history, conversation list.
Fixes #
doc: https://shimo.im/docs/vVAXMJ6PZ2IwQK3m
=> feat: add more chat api

apiserver/pkg/application/application.go
=> fix: application graph cant update llm name

apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/impl/modelservice.resolvers.go, apiserver/graph/schema/modelservice.gql, apiserver/graph/schema/modelservice.graphqls, apiserver/pkg/embedder/embedder.go, apiserver/pkg/modelservice/modelservice.go, apiserver/pkg/modelservice/sort.go, apiserver/pkg/modelservice/sort_test.go, gqlgen.yaml
/kind feature
feat: list llms and embedders
Fixes #https://github.com/kubeagi/arcadia/issues/401
=> feat: list llms and embedders

apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/schema/entrypoint.graphqls, apiserver/graph/schema/modelservice.gql, apiserver/pkg/common/endpoint.go, apiserver/pkg/datasource/datasource.go, apiserver/pkg/embedder/embedder.go, apiserver/pkg/llm/llm.go, deploy/llms/Dockerfile.fastchat-worker, pkg/arctl/datasource.go
=> chore: Update auth gql & related pkg

api/app-node/prompt/v1alpha1/prompttemplate.go, api/app-node/prompt/v1alpha1/prompttemplate_types.go, apiserver/pkg/application/application.go, config/crd/bases/prompt.arcadia.kubeagi.k8s.com.cn_prompts.yaml, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/crds/prompt.arcadia.kubeagi.k8s.com.cn_prompts.yaml
=> feat: when no userPrompt setting, we use default one

pkg/worker/devices.go, pkg/worker/runner.go
=> feat: enable multiple gpus(single node) in runner Fastchat

apiserver/pkg/common/common.go
=> feat: add a new intermediate status OfflineInProgress

apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/impl/modelservice.resolvers.go, apiserver/graph/schema/modelservice.gql, apiserver/graph/schema/modelservice.graphqls, apiserver/pkg/embedder/embedder.go, apiserver/pkg/llm/llm.go, apiserver/pkg/modelservice/modelservice.go, controllers/llm_controller.go, gqlgen.yaml
=> feat: add checkModelService API & fix bug

api/base/v1alpha1/worker.go, config/samples/arcadia_v1alpha1_worker_baichuan2-7b.yaml, config/samples/arcadia_v1alpha1_worker_bge-large-zh-v1.5.yaml, config/samples/arcadia_v1alpha1_worker_qwen-7b-chat.yaml
=> chore: use same common spec in worker's llm/worker

apiserver/graph/schema/modelservice.gql, apiserver/pkg/embedder/embedder.go, apiserver/pkg/llm/llm.go, apiserver/pkg/worker/worker.go
=> fix: unmilited page size not working in llm/embedder

apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/impl/embedder.resolvers.go, apiserver/graph/impl/modelservice.resolvers.go, apiserver/graph/schema/embedder.graphqls, apiserver/graph/schema/llm.graphqls, apiserver/graph/schema/modelservice.graphqls, apiserver/pkg/embedder/embedder.go, apiserver/pkg/llm/llm.go, apiserver/pkg/modelservice/modelservice.go
=> chore: refactor update/delete llm&embedder func

apiserver/pkg/application/application.go, apiserver/pkg/auth/auth.go, apiserver/pkg/common/common.go, apiserver/pkg/dataset/dataset.go, apiserver/pkg/datasource/datasource.go, apiserver/pkg/embedder/embedder.go, apiserver/pkg/knowledgebase/knowledgebase.go, apiserver/pkg/llm/llm.go, apiserver/pkg/model/model.go, apiserver/pkg/versioneddataset/versioned_dataset.go, apiserver/pkg/worker/worker.go
=> feat: set creator value in apiserver

apiserver/pkg/dataset/dataset.go
/kind bug
fix: dataset is not configured field fields
Fix https://github.com/kubeagi/arcadia/issues/469
=> fix: dataset is not configured field fields

.github/workflows/image_build.yml, .github/workflows/release_version.yaml, .goreleaser.yaml
=> chore: add version release action

apiserver/pkg/common/schema.go
=> chore: fix update embedder bug

api/app-node/chain/v1alpha1/llmchain_types.go, apiserver/pkg/application/application.go, config/crd/bases/chain.arcadia.kubeagi.k8s.com.cn_llmchains.yaml, config/crd/bases/chain.arcadia.kubeagi.k8s.com.cn_retrievalqachains.yaml, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/crds/chain.arcadia.kubeagi.k8s.com.cn_llmchains.yaml, deploy/charts/arcadia/crds/chain.arcadia.kubeagi.k8s.com.cn_retrievalqachains.yaml
=> chore: update some default value

.goreleaser.yaml
/kind cleanup
fix: gorelease ignore branch merge messages
Fixes #
=> fix: gorelease ignore branch merge messages

apiserver/pkg/model/model.go
/kind bug
correct the totalCount value returned by the listModels API
Fixes #484
=> fix: correct the totalCount value returned by the listModels API

apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/schema/dataprocessing.gql, apiserver/graph/schema/dataprocessing.graphqls, data-processing/data_manipulation/data_store_process/minio_store_process.py, data-processing/data_manipulation/database_operate/data_process_db_operate.py, data-processing/data_manipulation/database_operate/data_process_detail_db_operate.py, data-processing/data_manipulation/database_operate/data_process_document_chunk_db_operate.py, data-processing/data_manipulation/database_operate/data_process_log_db_operate.py, data-processing/data_manipulation/file_handle/common_handle.py, data-processing/data_manipulation/file_handle/pdf_handle.py, data-processing/data_manipulation/file_handle/word_handle.py, data-processing/data_manipulation/llm_api_service/qa_provider_open_ai.py, data-processing/data_manipulation/llm_api_service/qa_provider_zhi_pu_ai_online.py, data-processing/data_manipulation/service/data_process_service.py, data-processing/data_manipulation/utils/file_utils.py, data-processing/db-scripts/init-database-schema.sql, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/pg-init-data-configmap.yaml
Add the basic function for the data lineage and error log.
Feats #430
=> feat:Add the basic function for the data lineage and error log.

apiserver/pkg/model/model.go, apiserver/pkg/versioneddataset/versioned_dataset.go
/kind bug
fix: non-admin users are unable to access the data
Fixes #
=> fix: non-admin users are unable to access the data

apiserver/service/minio_server.go
/kind bug
fix: read the bucketname from the request header
Fixes #
=> fix: read the bucketname from the request header

apiserver/pkg/dataset/dataset.go, apiserver/pkg/versioneddataset/versioned_dataset.go
/kind bug
fix: update updatetime setting logic
Fixes #
=> fix: update updatetime setting logic

apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/impl/dataprocessing.resolvers.go, apiserver/graph/schema/dataprocessing.graphqls, apiserver/pkg/dataprocessing/dataprocessing.go, data-processing/data_manipulation/common/const.py, data-processing/data_manipulation/controller/data_process_controller.py, data-processing/data_manipulation/data_store_process/minio_store_process.py, data-processing/data_manipulation/database_operate/data_process_detail_db_operate.py, data-processing/data_manipulation/database_operate/data_process_stage_log_db_operate.py, data-processing/data_manipulation/file_handle/common_handle.py, data-processing/data_manipulation/service/data_process_service.py, data-processing/data_manipulation/utils/json_utils.py, data-processing/db-scripts/init-database-schema.sql, deploy/charts/arcadia/templates/pg-init-data-configmap.yaml, gqlgen.yaml
/kind feature
Add the basic function for the detail log.
=> feat:Add the basic function for the detail log.

pkg/application/base/node.go
=> fix: app run get error knowledgebase has no ns setting

apiserver/graph/generated/generated.go, apiserver/graph/impl/dataprocessing.resolvers.go, apiserver/graph/schema/dataprocessing.gql, apiserver/graph/schema/dataprocessing.graphqls, apiserver/pkg/dataprocessing/dataprocessing.go
Add gql for retrieving details logs.
=> chore:Add gql for retrieving details logs.

deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/config.yaml, deploy/charts/arcadia/templates/ingress-fastchat.yaml, deploy/charts/arcadia/templates/kubebb-menus.yaml, deploy/charts/arcadia/templates/kubebb-portal.yaml, deploy/charts/arcadia/templates/pg-init-data-configmap.yaml, deploy/charts/arcadia/templates/portal.yaml, deploy/charts/arcadia/values.yaml
/kind bug
chore: change the judgment condition of whether to install or not
Fixes #
=> chore: change the judgment condition of whether to install or not

apiserver/pkg/application/application.go, apiserver/pkg/common/common.go, apiserver/pkg/dataset/dataset.go, apiserver/pkg/datasource/datasource.go, apiserver/pkg/embedder/embedder.go, apiserver/pkg/knowledgebase/knowledgebase.go, apiserver/pkg/llm/llm.go, apiserver/pkg/model/model.go, apiserver/pkg/versioneddataset/versioned_dataset.go, apiserver/pkg/worker/worker.go
bug
Correct the totalCount value returned by some list API
Fixes #484
=> fix: correct the totalCount value returned by some list API

apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/schema/worker.gql, apiserver/graph/schema/worker.graphqls, apiserver/pkg/worker/worker.go
/kind feat
Fixes #510 
Fixes #524
=> feat: able to configure ray when create/update worker

pkg/worker/worker.go
=> fix: remove slash in hostpath when using datasource rdma

apiserver/docs/docs.go, apiserver/docs/swagger.json, apiserver/docs/swagger.yaml, apiserver/service/minio_server.go
/kind doc
chore: add swagger doc for GetSuccessChunks
For https://github.com/kubeagi/arcadia/issues/447
=> chore: add swagger doc for GetSuccessChunks

apiserver/docs/docs.go, apiserver/docs/swagger.json, apiserver/docs/swagger.yaml, apiserver/service/minio_server.go
/kind doc
chore: add swagger doc
For https://github.com/kubeagi/arcadia/issues/447
=> chore: add swagger doc

pkg/worker/worker.go
=> fix: skip to create embedder if worker is utilizing vllm

go.mod, go.sum
/kind bug
Fixes #
upstream change to https://github.com/Abirdcfly/langchaingo/tree/arcadia
=> fix: langchaingo upstream update

.github/workflows/pgvector_image_build.yml, api/base/v1alpha1/knowledgebase.go, controllers/app-node/chain/llmchain_controller.go, controllers/app-node/chain/retrieval_qa_chain_controller.go, controllers/app-node/prompt/prompt_controller.go, controllers/app-node/retriever/knowledgebase_retriever_controller.go, controllers/base/application_controller.go, controllers/base/knowledgebase_controller.go, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/config.yaml, deploy/charts/arcadia/templates/post-vectorstore.yaml, deploy/charts/arcadia/values.yaml, main.go, pkg/llms/zhipuai/api.go, pkg/vectorstore/pgvector.go, pkg/vectorstore/vectorstore.go, tests/deploy-values.yaml, tests/example-test.sh
/kind feature
With `pgvector` support, we can perform more fine-grained operations, such as incrementally updating vector data in behavioral units, which this pr implements. Note that after updating `qa.csv` in-place, you need to modify the annotation of knowlegebase to trigger the reconcile : `arcadia.kubeagi.k8s.com.cn/update-source-file-time`
Fixes #
=> feat: knowledgebase support more granular update

api/app-node/chain/v1alpha1/llmchain_types.go, apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/schema/application.gql, apiserver/graph/schema/application.graphqls, apiserver/pkg/application/application.go, config/crd/bases/chain.arcadia.kubeagi.k8s.com.cn_apichains.yaml, config/crd/bases/chain.arcadia.kubeagi.k8s.com.cn_llmchains.yaml, config/crd/bases/chain.arcadia.kubeagi.k8s.com.cn_retrievalqachains.yaml, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/crds/chain.arcadia.kubeagi.k8s.com.cn_apichains.yaml, deploy/charts/arcadia/crds/chain.arcadia.kubeagi.k8s.com.cn_llmchains.yaml, deploy/charts/arcadia/crds/chain.arcadia.kubeagi.k8s.com.cn_retrievalqachains.yaml
=> feat: add maxTokens in apiserver

pkg/arctl/download/download.go, pkg/arctl/eval.go
/kind feature
feat: add a command to download a file
Fixes #
```shell
$ ./main -n=arcadia eval download --rag=test --application=def
copy source /arcadia/dataset/dataset/v1/test/ca.crt to dataset/dataset/v1/test/ca.crt
copy source /arcadia/dataset/dataset/v1/test/ca.key to dataset/dataset/v1/test/ca.key
copy source /arcadia/dataset/dataset/v1/jira.txt to dataset/dataset/v1/jira.txt
$ tree dataset/
dataset/
└── dataset
└── v1
├── jira.txt
└── test
├── ca.crt
└── ca.key
3 directories, 3 files
```
=> feat: add a command to download a file

pkg/langchainwrap/llm.go, pkg/llms/llms.go, pkg/llms/zhipuai/langchainllm.go
=> chore: add new models supported by zhipuai

pkg/arctl/eval.go
/kind bug
chore: fix function call errors
Fixes #
=> chore: fix function call errors

pkg/worker/worker.go
/kind bug
Update displayname in modelserver
For https://github.com/kubeagi/arcadia/issues/564
=> Update displayname in modelserver

pkg/worker/worker.go
/kind feat
Fixes #563 
Reference： https://kubernetes.io/docs/tasks/debug/debug-application/debug-pods/#my-pod-stays-waiting
=> feat: handle pod state Waiting in worker

.github/workflows/data_processing_image_build_test.yml, .github/workflows/image_build.yml
=> fix: recover data-processing image build action

apiserver/pkg/worker/worker.go
/kind bug
Correctly display the field replicas
Fixes #
=> fix:the field replicas display

pypi/data-processing/src/data_store_process/minio_store_process.py, pypi/data-processing/src/file_handle/pdf_handle.py
/kind bug
fix:The 'chunk_overlap' parameter did not take effect during text splitting
fix:Convert error messages into Chinese
=> fix:The 'chunk_overlap' parameter did not take effect during text splitting

api/base/v1alpha1/common.go, api/base/v1alpha1/worker.go, apiserver/graph/impl/worker.resolvers.go, apiserver/pkg/common/common_list_resource.go, apiserver/pkg/modelservice/helper.go, apiserver/pkg/modelservice/modelservice.go, apiserver/pkg/worker/worker.go, controllers/base/embedder_controller.go, controllers/base/llm_controller.go, controllers/base/worker_controller.go, deploy/charts/arcadia/crds/arcadia.kubeagi.k8s.com.cn_workers.yaml
/kind bug
fix: too long to call listModelServices
Fix #537
=> fix: too long to call listModelServices

apiserver/pkg/worker/worker.go, controllers/base/worker_controller.go
=> fix: replce comma with underline in woker's model label

controllers/base/worker_controller.go
=> fix: shoud delete worker label with DeepCopied object

controllers/base/llm_controller.go, pypi/data-processing/src/llm_api_service/qa_provider_zhi_pu_ai_online.py
=> fix: set model in QAProviderZhiPuAIOnline

apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/schema/knowledgebase.gql, apiserver/graph/schema/knowledgebase.graphqls, apiserver/pkg/knowledgebase/knowledgebase.go
=> fix: add new filed embeddderType in apiserver's knowledgebase model

api/app-node/chain/v1alpha1/llmchain_types.go, apiserver/pkg/application/application.go, apiserver/pkg/chat/chat.go, apiserver/service/chat.go, config/crd/bases/chain.arcadia.kubeagi.k8s.com.cn_apichains.yaml, config/crd/bases/chain.arcadia.kubeagi.k8s.com.cn_llmchains.yaml, config/crd/bases/chain.arcadia.kubeagi.k8s.com.cn_retrievalqachains.yaml, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/crds/chain.arcadia.kubeagi.k8s.com.cn_apichains.yaml, deploy/charts/arcadia/crds/chain.arcadia.kubeagi.k8s.com.cn_llmchains.yaml, deploy/charts/arcadia/crds/chain.arcadia.kubeagi.k8s.com.cn_retrievalqachains.yaml, pkg/appruntime/app_runtime.go, pkg/appruntime/chain/retrievalqachain.go
=> fix: qachain set history will get error

apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/schema/embedder.graphqls, apiserver/graph/schema/llm.graphqls, apiserver/pkg/embedder/embedder.go, apiserver/pkg/llm/llm.go, apiserver/pkg/modelservice/modelservice.go
=> feat: able to set/update models in LLM and Embedder

pypi/data-processing/src/file_handle/common_handle.py
able to use openai in data-processing
Fixes #619
=> feat:able to use openai in data-processing

pkg/arctl/eval.go
bug
the command `arctl gen_test_dataset` recursively reads files
Fixes #
=> fix: the command `arctl gen_test_dataset` recursively reads files

deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/pg-init-data-configmap.yaml, pypi/data-processing/Dockerfile, pypi/data-processing/db-scripts/init-database-schema.sql, pypi/data-processing/requirements.txt, pypi/data-processing/src/common/log_tag_const.py, pypi/data-processing/src/database_operate/dp_document_image_db_operate.py, pypi/data-processing/src/database_operate/dp_document_web_url_db_operate.py, pypi/data-processing/src/utils/web_url_utils.py
Real-time data access
Fixes #512
=> feat:Real-time data access

.github/workflows/eval_image_build.yml, .github/workflows/eval_image_build_test.yml, deploy/evaluation/Dockerfile
=> chore: add evaluation CLI dockerfile

pypi/data-processing/requirements.txt
=> fix:Updating requirements

pkg/appruntime/retriever/knowledgebaseretriever.go, tests/example-test.sh
=> fix: doc score need update

pkg/arctl/eval.go
/kind feature
feat: support for downloading data from versioneddatasets
Fixes #
```yaml
apiVersion: evaluation.arcadia.kubeagi.k8s.com.cn/v1alpha1
kind: RAG
metadata:
name: test-vds
namespace: rag-eval
spec:
storage:
storageClassName: openebs-hostpath
accessModes:
- ReadWriteOnce
resources:
requests:
storage: 1Gi
application:
apiGroup: arcadia.kubeagi.k8s.com.cn/v1alpha1
kind: Application
name: rag-test
namespace: rag-eval
datasets:
- files:
- a.csv
- abc.csv
source:
apiGroup: arcadia.kubeagi.k8s.com.cn
kind: Datasource
name: arcadia-minio
namespace: rag-eval
- files:
- csvfolder/qa.csv # full path
- csvfolder/info/abc-2023_final.csv
source:
apiGroup: arcadia.kubeagi.k8s.com.cn
kind: VersionedDataset
name: abc
namespace: arcadia
judge_llm:
apiGroup: judge
kind: llm
name: def
metrics: [] …
```
=> feat: support for downloading data from versioneddatasets

pkg/appruntime/chain/llmchain.go, pkg/appruntime/prompt/prompt.go
fix potential issue in the context of prompt
=> fix potential issue in the context of prompt

apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/schema/gpt.graphqls, apiserver/pkg/chat/chat_server.go, apiserver/pkg/chat/storage/storage.go, apiserver/pkg/chat/storage/storage_memory.go, apiserver/pkg/chat/storage/storage_postgresql.go, apiserver/pkg/gpt/gpt.go
=> fix: gpt hot use storage interface

api/base/v1alpha1/common.go, api/base/v1alpha1/embedder.go, api/base/v1alpha1/knowledgebase_types.go, api/base/v1alpha1/llm.go, config/crd/bases/arcadia.kubeagi.k8s.com.cn_datasources.yaml, config/crd/bases/arcadia.kubeagi.k8s.com.cn_embedders.yaml, config/crd/bases/arcadia.kubeagi.k8s.com.cn_llms.yaml, config/crd/bases/arcadia.kubeagi.k8s.com.cn_vectorstores.yaml, controllers/base/knowledgebase_controller.go, deploy/charts/arcadia/crds/arcadia.kubeagi.k8s.com.cn_datasources.yaml, deploy/charts/arcadia/crds/arcadia.kubeagi.k8s.com.cn_embedders.yaml, deploy/charts/arcadia/crds/arcadia.kubeagi.k8s.com.cn_llms.yaml, deploy/charts/arcadia/crds/arcadia.kubeagi.k8s.com.cn_vectorstores.yaml, pkg/appruntime/retriever/knowledgebaseretriever.go, pkg/langchainwrap/embedder.go, pkg/langchainwrap/llm.go
=> feat: able to use openai as the embedder in knowledgebase

pypi/ragas_once/ragas_once/cli.py, pypi/ragas_once/ragas_once/wrapper.py
=> feat: result & summary CSV file output

pypi/ragas_once/README.md, pypi/ragas_once/ragas_once/cli.py
=> chore: fix ragas-once readme typo & bug

apiserver/docs/docs.go, apiserver/docs/swagger.json, apiserver/docs/swagger.yaml, apiserver/pkg/chat/chat_server.go, apiserver/pkg/chat/rest_type.go, apiserver/pkg/chat/storage/storage.go, apiserver/service/chat.go, controllers/base/knowledgebase_controller.go, controllers/base/model_controller.go, pkg/appruntime/chain/apichain.go, pkg/appruntime/chain/common.go, pkg/appruntime/chain/llmchain.go, pkg/appruntime/chain/retrievalqachain.go, pkg/appruntime/knowledgebase/knowledgebase.go, pkg/datasource/datasource.go, tests/example-test.sh
=> feat: add chat latency and api: generate prompt starters

api/evaluation/v1alpha1/common.go, apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/impl/rag.resolvers.go, apiserver/graph/schema/k8s.graphqls, apiserver/graph/schema/rag.gql, apiserver/graph/schema/rag.graphqls, apiserver/pkg/common/common_filter.go, apiserver/pkg/rag/rag.go
/kind feature
feat: graphql add api to create rag
Fixes #
=> feat: graphql add api to create rag

pypi/data-processing/requirements.txt, pypi/data-processing/src/data_store_process/minio_store_process.py, pypi/data-processing/src/database_operate/data_process_detail_db_operate.py, pypi/data-processing/src/database_operate/dp_document_image_db_operate.py, pypi/data-processing/src/document_loaders/async_playwright.py, pypi/data-processing/src/document_loaders/base.py, pypi/data-processing/src/file_handle/common_handle.py, pypi/data-processing/src/file_handle/web_handle.py, pypi/data-processing/src/file_handle/word_handle.py, pypi/data-processing/src/llm_api_service/qa_provider_zhi_pu_ai_online.py, pypi/data-processing/src/service/data_process_service.py, pypi/data-processing/src/utils/json_utils.py, pypi/data-processing/src/utils/web_url_utils.py
=> feat:Splitting website data

pkg/arctl/eval.go, pkg/evaluation/evaluation.go
/kind feature
feat: arctl support merge files
Fix https://github.com/kubeagi/arcadia/issues/652
=> feat: arctl support merge files

apiserver/pkg/application/application.go, pkg/appruntime/chain/common.go, pkg/appruntime/tools/bingsearch/bing.go, pkg/appruntime/tools/bingsearch/bing_test.go, pkg/appruntime/tools/bingsearch/client.go, pkg/appruntime/tools/bingsearch/doc.go, pkg/appruntime/tools/bingsearch/resp.go
/kind feature
/kind bug
1. graphql update to remove tool config may not work
2. bingsearch add more config, export result count to crd spec.
3. bingsearch now parse webpage and news type.
4. add more test for bingsearch.
Fixes #
=> feat: bingsearch add more config

apiserver/pkg/worker/worker.go, pkg/appruntime/app_runtime.go, pkg/arctl/eval.go, pkg/documentloaders/qa_csv.go, pkg/evaluation/evaluation.go
=> fix: skip invalid document in evaluation

pypi/ragas_once/ragas_once/cli.py
=> chore: fix ragas_once cli bug

.github/workflows/eval_image_build.yml, .github/workflows/eval_image_build_test.yml
=> chore: fix eval_image_build workflow

apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/impl/rag.resolvers.go, apiserver/graph/schema/rag.graphqls, apiserver/pkg/rag/rag.go
/kind feature
graphQL: add api to update rag
Fixes #565
=> feat: graphQL add api to update rag

deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/pg-init-data-configmap.yaml, pypi/data-processing/db-scripts/init-database-schema.sql, pypi/data-processing/src/database_operate/dp_document_qa_remove_duplicate_db_operate.py, pypi/data-processing/src/embeddings/embeddings.py, pypi/data-processing/src/embeddings/openai_embeddings.py, pypi/data-processing/src/service/data_process_qa_remove_duplicate.py
=> feat:QA remove duplicate

pkg/arctl/eval.go
/king bug
fix: datasource and dataset are using the wrong bucket in command arctl
Fix https://github.com/kubeagi/arcadia/issues/662
=> fix: datasource and dataset are using the wrong bucket in command arctl

config/rbac/role.yaml, controllers/base/namespace_controller.go, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/rag_job_rbac.yaml, deploy/charts/arcadia/templates/rbac.yaml, pkg/evaluation/jobs.go
/kind feature
feat: namespace controller creates the rabc needed for the job
Fix https://github.com/kubeagi/arcadia/issues/629
=> feat: namespace controller creates the rabc needed for the job

deploy/evaluation/Dockerfile, pkg/evaluation/jobs.go
=> chore: fix eval dockerfile

Makefile, api/base/v1alpha1/application_types.go, apiserver/docs/docs.go, apiserver/docs/swagger.json, apiserver/docs/swagger.yaml, apiserver/main.go, apiserver/pkg/chat/chat_docs.go, apiserver/pkg/chat/rest_type.go, apiserver/pkg/common/common.go, apiserver/pkg/common/schema.go, apiserver/service/chat.go, apiserver/service/graph_api_server.go, apiserver/service/minio_server.go, apiserver/service/router.go, controllers/base/knowledgebase_controller.go, pkg/appruntime/llm/llm.go, pkg/config/config.go, pkg/config/config_type.go, pkg/documentloaders/qa_csv.go, pkg/langchainwrap/embedder.go, pkg/langchainwrap/llm.go, pkg/vectorstore/vectorstore.go
Fixes #553 
Configurations for the following test :
- filesize: 300kb
- lllm: qwen7b
- embedding: bge
- gpu: 4090
When using swagger document:
=> feat: able to generate embeddings and summarization for documents  in a conversation

apiserver/pkg/rag/rag.go
/kind bug
can't create pvc
Fixes #
=> can't create pvc

pypi/data-processing/examples/qa_deduplicate/qa_remove_duplicate.py, pypi/data-processing/src/service/data_process_qa_remove_duplicate.py
=> fix:add an example on QA deduplicate

apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/schema/k8s.graphqls, apiserver/graph/schema/rag.graphqls, apiserver/pkg/rag/rag.go
/kind feature
feat: set to storage as a non-required field
Fixes #
=> feat: set to storage as a non-required field

apiserver/graph/schema/application.gql
=> fix: controller should watch sub resource update

controllers/evaluation/rag_controller.go
/kind feature
feat: when a task fails, display the failure time
Fixes #
=> feat: when a task fails, display the failure time

apiserver/docs/docs.go, apiserver/docs/swagger.json, apiserver/docs/swagger.yaml, apiserver/pkg/chat/chat_docs.go, apiserver/pkg/chat/rest_type.go, apiserver/pkg/chat/storage/storage.go, apiserver/pkg/chat/storage/storage_memory.go, apiserver/pkg/chat/storage/storage_postgresql.go, apiserver/service/chat.go
=> feat: able to store chat document

apiserver/pkg/chat/chat_docs.go, apiserver/service/chat.go
=> feat: support streaming in chat docs

apiserver/pkg/auth/auth.go, apiserver/service/chat.go, apiserver/service/minio_server.go
/kind feature
feat: apiserver authentication support different groups
Fix #701
=> feat: apiserver authentication support different groups

deploy/charts/arcadia/Chart.lock, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/charts/fastchat/Chart.yaml, deploy/charts/arcadia/charts/fastchat/values.yaml, deploy/charts/arcadia/values.yaml, deploy/llms/Dockerfile.fastchat-server
New fastchat server image `kubeagi/arcadia-fastchat:v0.2.0` has now pushed to docker hub.
Fixes #697
=> chore: update llms dockerfile

apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/schema/dataprocessing.graphqls, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/pg-init-data-configmap.yaml, pypi/data-processing/db-scripts/init-database-schema.sql, pypi/data-processing/src/common/log_tag_const.py, pypi/data-processing/src/data_store_process/minio_store_process.py, pypi/data-processing/src/database_operate/data_process_detail_db_operate.py, pypi/data-processing/src/database_operate/dp_document_qa_remove_duplicate_db_operate.py, pypi/data-processing/src/document_chunks/base.py, pypi/data-processing/src/document_chunks/spacy_text_splitter.py, pypi/data-processing/src/document_loaders/async_playwright.py, pypi/data-processing/src/document_loaders/docx.py, pypi/data-processing/src/document_loaders/pdf.py, pypi/data-processing/src/embeddings/openai_embeddings.py, pypi/data-processing/src/file_handle/base.py, pypi/data-processing/src/file_handle/common_handle.py, pypi/data-processing/src/file_handle/pdf_handle.py, pypi/data-processing/src/file_handle/web_handle.py, pypi/data-processing/src/file_handle/word_handle.py, pypi/data-processing/src/kube/client.py, pypi/data-processing/src/kube/custom_resources.py, pypi/data-processing/src/kube/dataset_cr.py, pypi/data-processing/src/kube/model_cr.py, pypi/data-processing/src/service/data_process_qa_remove_duplicate.py, pypi/data-processing/src/utils/file_utils.py, pypi/data-processing/src/utils/json_utils.py
feat: Remove duplicate QA data.
chore: Optimized code for chunk and handle sections.
Fixes #431
=> feat:deduplicate QA

apiserver/pkg/chat/chat_docs.go, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/ingress-apiserver.yaml, deploy/charts/arcadia/templates/ingress-fastchat.yaml
=> chore: add some logs in chat doc;increaset ingress timeout

apiserver/pkg/chat/chat_server.go, controllers/base/knowledgebase_controller.go, tests/example-test.sh
=> fix: prompt-starter api cant get data when use knowledgebase

apiserver/pkg/chat/rest_type.go
=> chore: add omitpty to doc in ConversationDocsRespBody

.github/workflows/example_test.yaml, README.md
Update npm repo host and README
=> Update npm repo host and README

pkg/evaluation/jobs.go
/kind bug
fix: adapting ragas_once parameter changes
For https://github.com/kubeagi/arcadia/pull/694#issuecomment-1918877529
=> fix: adapting ragas_once parameter changes

apiserver/config/config.go, apiserver/docs/docs.go, apiserver/docs/swagger.json, apiserver/docs/swagger.yaml, apiserver/pkg/rag/report.go, apiserver/service/minio_server.go, apiserver/service/rag_server.go, apiserver/service/router.go
/kind feature
feat: add a new api to get rag evaluation report
Fix https://github.com/kubeagi/arcadia/issues/684
=> feat: add a new api to get rag evaluation report

apiserver/pkg/chat/chat_docs.go
Fixes #721 
This is only a temporary fix. We should consider to provide a consistent way to chat wiht documents just like other common chat in appruntime. Let's do this in v0.3
=> fix: pass chain call options to chat_docs

pkg/appruntime/chain/retrievalqachain.go, pkg/evaluation/evaluation.go
=> fix: add empty history for evaluation run

deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/rag_job_rbac.yaml
/kind bug
fix: add permissions for arctl
Fixes #
=> fix: add permissions for arctl

.github/workflows/eval_image_build.yml, .github/workflows/eval_image_build_test.yml
=> chore: build eval image upon all pkg update

apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/schema/dataprocessing.gql, apiserver/graph/schema/dataprocessing.graphqls
details return deduplication configuration information
=> feat:details return deduplication configuration information

deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/rag_job_rbac.yaml
/kind bug
fix: prompt is using the wrong group
Fixes #
=> fix: prompt is using the wrong group

README.md, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/values.yaml, examples/README.md
=> chore: update docs and use standard as the default storageclass

controllers/evaluation/rag_controller.go, main.go
/kind bug
fix: delete the rag and clean up the minio files at the same time
Fixes #
=> fix: delete the rag and clean up the minio files at the same time

.github/workflows/eval_image_build.yml, .github/workflows/eval_image_build_test.yml
=> fix: eval image build action

apiserver/pkg/rag/rag.go
/kind feature
feat: add creator for rag
Fix https://github.com/kubeagi/arcadia/issues/736
=> feat: add creator for rag

controllers/base/namespace_controller.go, main.go
/kind bug
fix: too many unexpected logs in arcadia-controller during startup
Fix https://github.com/kubeagi/arcadia/issues/742
=> fix: too many unexpected logs in arcadia-controller during startup

deploy/charts/arcadia/README.md
=> feat: add README.md for arcadia chart

apiserver/service/chat.go
/kind fix
Fixes #
It takes too long before summary got generated , so ticker  check is not appropriate.
=> fix: remove ticker check in chat docs

apiserver/service/chat.go
=> fix: init a start time when chat documents

apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/impl/rag.resolvers.go, apiserver/graph/schema/rag.graphqls, apiserver/pkg/rag/rag.go, gqlgen.yaml
/kind feature
Add api to support copying existing rag
Fixes #700
=> feat: Add api to support copying existing rag

pkg/arctl/eval.go, pkg/evaluation/evaluation.go
=> chore: add limit to context len in eval data gen

apiserver/pkg/rag/report.go, pkg/evaluation/evaluation.go, pkg/evaluation/output.go
/kind feature
Fix https://github.com/kubeagi/arcadia/issues/764
=> add a new column latency in rag eval dataset row

apiserver/docs/docs.go, apiserver/docs/swagger.json, apiserver/docs/swagger.yaml, apiserver/pkg/rag/report.go, apiserver/service/rag_server.go
/kind bug
refactor: change the report's scatter structure
For https://github.com/kubeagi/ops-console/issues/223
=> refactor: change the report's scatter structure

api/base/v1alpha1/model.go, api/base/v1alpha1/model_types.go, config/crd/bases/arcadia.kubeagi.k8s.com.cn_models.yaml, controllers/base/model_controller.go, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/crds/arcadia.kubeagi.k8s.com.cn_models.yaml, deploy/charts/arcadia/templates/post-models.yaml
=> add more info to models

api/app-node/agent/v1alpha1/agent_types.go, config/crd/bases/arcadia.kubeagi.k8s.com.cn_agents.yaml, config/rbac/role.yaml, controllers/base/application_controller.go, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/crds/arcadia.kubeagi.k8s.com.cn_agents.yaml, deploy/charts/arcadia/templates/rbac.yaml, deploy/charts/arcadia/values.yaml, main.go, pkg/appruntime/agent/executor.go, pkg/appruntime/documentloader/documentloader.go, pkg/appruntime/prompt/prompt.go, pypi/data-processing/requirements.txt
1. Fix rbac issue of documentloader
2. Add showToolAction to configure whether to show the streaming output of tool
3. add calculator tool
=> fix documentloader issue and add calculator tool

.github/workflows/data_processing_image_build_test.yml, pypi/data-processing/Dockerfile
the dataprocessing image cannot be build.
=> fix:the dataprocessing image cannot be build.

.github/workflows/worker_image_build_test.yml, deploy/llms/Dockerfile.fastchat-worker, deploy/llms/Dockerfile.fastchat-worker-vllm, deploy/llms/start-worker.sh
/kind feature
fix: upgrade fastchat to v0.2.36
Fix https://github.com/kubeagi/arcadia/issues/748
=> fix: upgrade fastchat to v0.2.36

deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/values.yaml
=> chore: upgrade fastchat image to v0.2.36

deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/agent-portal.yaml
=> fix: should use port 3000 in agentportal svc

deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/values.yaml
enable minio console by default
/kind feature
enable minio console by default  to upload model files easily for users.
Fixes #
=> enable minio console by default

PROJECT, api/app-node/chain/v1alpha1/llmchain_types.go, api/base/v1alpha1/application.go, apiserver/docs/docs.go, apiserver/docs/swagger.json, apiserver/docs/swagger.yaml, apiserver/pkg/application/application.go, apiserver/pkg/chat/chat_docs.go, apiserver/pkg/chat/chat_server.go, apiserver/pkg/chat/rest_type.go, apiserver/pkg/chat/storage/storage.go, apiserver/pkg/chat/storage/storage_postgresql.go, apiserver/service/chat.go, config/crd/bases/chain.arcadia.kubeagi.k8s.com.cn_apichains.yaml, config/crd/bases/chain.arcadia.kubeagi.k8s.com.cn_llmchains.yaml, config/crd/bases/chain.arcadia.kubeagi.k8s.com.cn_retrievalqachains.yaml, config/crd/kustomization.yaml, config/samples/app_llmchain_abstract.yaml, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/crds/chain.arcadia.kubeagi.k8s.com.cn_apichains.yaml, deploy/charts/arcadia/crds/chain.arcadia.kubeagi.k8s.com.cn_llmchains.yaml, deploy/charts/arcadia/crds/chain.arcadia.kubeagi.k8s.com.cn_retrievalqachains.yaml, pkg/appruntime/chain/llmchain.go, pkg/appruntime/chain/mpchain.go, pkg/appruntime/chain/retrievalqachain.go, pkg/appruntime/documentloader/documentloader.go
=> refactor(file): files upload and processing during agent chat

apiserver/docs/docs.go, apiserver/docs/swagger.json, apiserver/docs/swagger.yaml, apiserver/pkg/chat/chat_docs.go, apiserver/pkg/chat/chat_server.go, apiserver/pkg/chat/rest_type.go
=> fix: remove tag in chat document and add document to chat resp

config/samples/app_llmchain_abstract.yaml, pkg/appruntime/chain/mpchain.go
=> fix: set MaxNumberOfConcurrent to 1 if not provided

deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/post-models.yaml
/kind feature
chore: add revision field.
Supports automatically pulling model files from the model repository.
Fixes #
=> chore: add revision field

pkg/worker/runner.go, pkg/worker/worker.go
=> chore: kubeagi-runner supports automatically pulling model files

apiserver/docs/docs.go, apiserver/docs/swagger.json, apiserver/docs/swagger.yaml, apiserver/pkg/common/read_csv.go, apiserver/pkg/common/read_csv_test.go, apiserver/service/minio_server.go, controllers/base/namespace_controller.go, pkg/datasource/oss.go
/kind feature
feat: support editing csv file online
Fixes #
=> feat: support editing csv file online

apiserver/pkg/chat/storage/storage.go
=> fix: files should be string not text[]

config/samples/app_llmchain_chat_with_bot_tool.yaml, tests/example-test.sh
34d7fc1ee7e58c4b1b4c0232bdc6f5fc624957a9 add tool test into github action to use gemini llm
also fix gemini stream issue Close #818
the gemini stream issue is because https://github.com/tmc/langchaingo/pull/663
用 gemini 来测试agent的工具，避免本地模型因为fastchat或者gpu造成干扰：（因为bing付费问题，暂时没有开启bing测试），从测试看，不一定每次都能成功答出希望的回答。
常见的错误有：
```
"run node agent-node: error when call agent: agent not finished before max iterations"
"run node agent-node: error when call agent: unable to parse agent output: I cannot answer this question because the required tool, Web Scraper, is not available."
"run node agent-node: error when call agent: unable to parse agent output: I cannot find the answer to your question."
"run node agent-node: error when call agent: unable to parse agent output: This question cannot be answered …
```
=> test: enable agent test in github action anf fix stream issue

deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/apiserver.yaml, deploy/charts/arcadia/values.yaml, pkg/tools/bingsearch/client.go, pkg/tools/weather/weatherapi.go
/kind cleanup
chore: remove WEATHER_API_KEY,BING_KEY environment variable
Fix https://github.com/kubeagi/arcadia/issues/825
=> chore: remove WEATHER_API_KEY,BING_KEY environment variable

pkg/worker/runner.go
/kind bug
also add the argument `revision` for HuggingFaceRepo
Fixes #
Test results:
=> fix: also add the argument `revision` for HuggingFaceRepo

apiserver/pkg/modelservice/modelservice.go
=> fix: failed to update model service

pkg/worker/runner.go
/kind bug
fix: vllm needs to use gpu
Fixes #
=> fix: vllm needs to use gpu

pypi/data-processing/src/common/config.py, pypi/data-processing/src/server.py
=> fix:Convert chunkSize and worker values to int type.

deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/config.yaml, deploy/charts/arcadia/values.yaml
=> chore: add worker and chunksize config in data-processing charts

apiserver/service/minio_server.go
bug
Directly edit the svc file when the version is invalid & synchronize tags
Fixes #
=> fix: Directly edit the svc file when the version is invalid & synchronize tags

api/base/v1alpha1/knowledgebase.go, api/base/v1alpha1/knowledgebase_types.go, apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/schema/knowledgebase.gql, apiserver/graph/schema/knowledgebase.graphqls, apiserver/pkg/knowledgebase/knowledgebase.go, config/crd/bases/arcadia.kubeagi.k8s.com.cn_knowledgebases.yaml, controllers/base/knowledgebase_controller.go, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/crds/arcadia.kubeagi.k8s.com.cn_knowledgebases.yaml
=> fix: add batchsize in embedding options

api/base/v1alpha1/model_types.go, apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/schema/model.graphqls, config/crd/bases/arcadia.kubeagi.k8s.com.cn_models.yaml, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/crds/arcadia.kubeagi.k8s.com.cn_models.yaml
/kind bug
chore: add modelsource field and update graphql definition
Fixes #
=> chore: add modelsource field and update graphql definition

api/base/v1alpha1/knowledgebase_types.go, apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/schema/knowledgebase.gql, apiserver/graph/schema/knowledgebase.graphqls, apiserver/pkg/knowledgebase/knowledgebase.go, config/crd/bases/arcadia.kubeagi.k8s.com.cn_knowledgebases.yaml, config/crd/bases/arcadia.kubeagi.k8s.com.cn_versioneddatasets.yaml, controllers/base/application_controller.go, controllers/base/knowledgebase_controller.go, controllers/base/worker_controller.go, deploy/charts/arcadia/crds/arcadia.kubeagi.k8s.com.cn_knowledgebases.yaml, deploy/charts/arcadia/crds/arcadia.kubeagi.k8s.com.cn_versioneddatasets.yaml, deploy/charts/arcadia/templates/ingress-apiserver.yaml, deploy/charts/arcadia/templates/ingress-minio.yaml, deploy/charts/arcadia/values.yaml
=> feat(knowledgebase): able to configure time cost of file processing

controllers/base/knowledgebase_controller.go
=> fix: odd number of arguments passed as key-value pairs for logging

pkg/worker/loader.go, pkg/worker/runner.go, pkg/worker/worker.go
/kind feature
chore: get the model files based on the modelsource field
Fixes #
=> chore: get the model files based on the modelsource field

config/samples/arcadia_v1alpha1_model_reranking_bce.yaml, controllers/base/knowledgebase_controller.go, pkg/appruntime/documentloader/documentloader.go, pkg/documentloaders/pdf.go, pkg/documentloaders/qa_csv.go, pkg/vectorstore/vectorstore.go
=> feat: show pdf info in reference

api/base/v1alpha1/datasource.go, api/base/v1alpha1/embedder.go, api/base/v1alpha1/knowledgebase.go, api/base/v1alpha1/knowledgebase_types.go, api/base/v1alpha1/vectorstore.go, apiserver/pkg/chat/chat_docs.go, config/crd/bases/arcadia.kubeagi.k8s.com.cn_knowledgebases.yaml, controllers/base/knowledgebase_controller.go, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/crds/arcadia.kubeagi.k8s.com.cn_knowledgebases.yaml
Fixes #
1. build a knowledgebase for conversation
2. able to process files whose source is  a `CR Datasource`
=> feat: build knowledgebase for conversation

apiserver/graph/schema/entrypoint.graphqls, apiserver/pkg/application/application.go, apiserver/pkg/dataset/dataset.go, apiserver/pkg/datasource/datasource.go, apiserver/pkg/embedder/embedder.go, apiserver/pkg/knowledgebase/knowledgebase.go, apiserver/pkg/llm/llm.go, apiserver/pkg/model/model.go, apiserver/pkg/modelservice/modelservice.go, apiserver/pkg/rag/rag.go, apiserver/pkg/versioneddataset/versioned_dataset.go, apiserver/pkg/worker/worker.go
/kind bug
fix: support getting all data
Fix https://github.com/kubeagi/arcadia/issues/838
=> fix: support getting all data

apiserver/service/chat.go, deploy/llms/Dockerfile.fastchat-worker-vllm, deploy/llms/utils.py, deploy/ray/Dockerfile
1. Fix conversation chat with doc for 1st time
2. Update ray to 2.9.3(vllm 0.3.3)
=> Fix conversation chat with doc for 1st time and update ray to 2.9.3(vllm 0.3.3)

apiserver/pkg/chat/chat_docs.go, apiserver/pkg/knowledgebase/knowledgebase.go, config/crd/kustomization.yaml, controllers/base/knowledgebase_controller.go, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/post-datasource.yaml
=> fix: use datasource as the default source in knowledgebase

pkg/worker/runner.go, pkg/worker/worker.go
1. Enable --enforce-eager by default
2. Fix NUMBER_GPUS issue
=> Enable --enforce-eager by default and fix NUMBER_GPUS issue

config/samples/arcadia_v1alpha1_worker_baichuan2-7b.yaml, config/samples/arcadia_v1alpha1_worker_bge-large-zh-v1.5.yaml, config/samples/arcadia_v1alpha1_worker_qwen-7b-chat.yaml, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/README.md, deploy/charts/arcadia/templates/config.yaml, deploy/charts/arcadia/templates/post-embedder.yaml, deploy/charts/arcadia/values.yaml, pkg/appruntime/chain/llmchain.go, pkg/appruntime/chain/retrievalqachain.go
=> fix: set/deploy a default embedder for kubeagi

pypi/data-processing/src/data_store_process/minio_store_process.py, pypi/data-processing/src/file_handle/common_handle.py
if QA deduplication is not selected, an error will be prompted.
=> fix:If QA deduplication is not selected, an error will be prompted.

pypi/data-processing/src/data_store_process/minio_store_process.py
the service cannot be started.
=> fix:the service cannot be started.

.github/workflows/codespell.yaml, apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, config/samples/app_llmchain_abstract.yaml, pkg/appruntime/chain/mpchain.go, tests/example-test.sh
=> fix: pdf summerize and and it to test

apiserver/graph/schema/model.gql, apiserver/pkg/common/common.go, apiserver/pkg/model/model.go
/kind feature
Complete the fields of the CR Model
Fixes #
=> feat: complete the fields of the CR Model

apiserver/service/minio_server.go
/kind bug
fix: when edit csv file, temporary file cannot be created
Fixes #
=> fix: when edit csv file, temporary file cannot be created

apiserver/pkg/forwardrepo/forward.go, apiserver/pkg/forwardrepo/huggingface.go, apiserver/pkg/forwardrepo/huggingface_test.go, apiserver/pkg/forwardrepo/huggingface_types.go, apiserver/pkg/forwardrepo/modelscope.go, apiserver/pkg/forwardrepo/modelscope_test.go, apiserver/pkg/forwardrepo/modelscope_types.go, apiserver/service/forward.go, apiserver/service/router.go
/kind feature
feat: get data from modelscope and huggingface
Fixes #
=> feat: get data from modelscope and huggingface

apiserver/service/router.go
/kind bug
fix: apiserver cors error
Fixes #
=> fix: apiserver cors error

apiserver/pkg/model/model.go
=> fix: should do nil check before set when create/update model

config/samples/ray.io_v1_raycluster.yaml, pkg/worker/runner.go
1. Refine the logic to add NUMBER_GPUS env
2. Support EXTRA_ARGS env in the worker
=> fix: refine ray logic and support extraAgrs in worker

apiserver/pkg/knowledgebase/knowledgebase.go
/kind bug
fix: list all files even no file status yet in knowledgebase
Fix https://github.com/kubeagi/arcadia/issues/874
=> fix: list all files even no file status yet in knowledgebase

apiserver/docs/docs.go, apiserver/docs/swagger.json, apiserver/docs/swagger.yaml, apiserver/pkg/chat/rest_type.go, apiserver/service/chat.go, apiserver/service/minio_server.go, apiserver/service/rag_server.go, tests/example-test.sh
=> fix: chat use header namespace

apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/schema/application.gql, apiserver/graph/schema/application.graphqls
=> feat: sync app config web ui for gql

apiserver/service/forward.go
/kind feature
feat: set apiserver proxy
Fixes #
=> feat: set apiserver proxy

apiserver/pkg/knowledgebase/knowledgebase.go
/kind bug
fix: check nil pointer
Fixes #
=> fix: check nil pointer

apiserver/pkg/chat/chat_server.go
=> fix: when knowledgebase has only chunk cant generate PromptStarter 

apiserver/pkg/chat/chat_server.go
/kind bug
本地的bge-enbedding没有发现，我们的zhipu embedding不支持空字符串做embedding，发出的请求是错的。
Fixes #
=> fix: zhipu embedding error with empty string

apiserver/docs/docs.go, apiserver/docs/swagger.json, apiserver/docs/swagger.yaml, apiserver/pkg/chat/rest_type.go, apiserver/service/chat.go, apiserver/service/rag_server.go
=> chore: add new param namespace in chat apis

pkg/config/config_type.go, pkg/worker/runner.go
=> fix: run worker atop of two gpus in one node

apiserver/pkg/knowledgebase/knowledgebase.go, controllers/app-node/retriever/rerank_retriever_controller.go, pkg/config/config.go, pkg/worker/runner.go
=> fix: able to update annotations in knowledgebase

apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/impl/gpt.resolvers.go, apiserver/graph/schema/gpt.graphqls, apiserver/pkg/gpt/gpt.go, apiserver/service/forward.go, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/config.yaml, deploy/charts/arcadia/values.yaml, gqlgen.yaml, pkg/config/config_type.go, pkg/config/gpts_config.go
=> feat: able to configure gpts categories

deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/config.yaml
/kind bug
fix: duplicate category id
Fixes #
=> fix: duplicate category id

apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/schema/datasource.gql, apiserver/graph/schema/datasource.graphqls, apiserver/pkg/datasource/datasource.go
=> feat: able to add pg datasource from apiserver

apiserver/graph/schema/gpt.gql
=> chore: add listGPTCategory in gpt.gql

apiserver/graph/schema/gpt.gql
=> fix: remove () in gql if no input required

apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/impl/gpt.resolvers.go, apiserver/graph/schema/gpt.gql, apiserver/graph/schema/gpt.graphqls, apiserver/pkg/common/common.go, apiserver/pkg/gpt/gpt.go, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/config.yaml, gqlgen.yaml, pkg/config/gpts_config.go
=> feat: add gpts url in gpts config and add api to return the gptsconfig

apiserver/graph/schema/versioned_dataset.gql, apiserver/pkg/versioneddataset/versioned_dataset.go
/kind feature
return the `versions` field of the file
Fixes #
=> feat: `versioneddataset` return the `versions` field of the file

deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/agent-portal.yaml
/kind bug
Fixes #
we should only cache `/_next`
=> fix(deploy): fix agent-portal ingress cache issue

apiserver/pkg/gpt/gpt.go, deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/templates/config.yaml, deploy/charts/arcadia/values.yaml
=> fix: filter recommend gpts

controllers/base/knowledgebase_controller.go
chore: knowledgebase add processing status
Fix https://github.com/kubeagi/arcadia/issues/922
=> chore: knowledgebase add processing status

.github/workflows/chart_lint_test.yaml, .github/workflows/release.yaml, deploy/charts/arcadia/templates/config.yaml, deploy/charts/arcadia/values.yaml
Fixes #
With thi pr merged, we do not need to bump chart version even for small changes which led to lots of tags got published.
=> chore: disable version increment check and publish a version manually

api/base/v1alpha1/application.go, apiserver/pkg/application/application.go, apiserver/pkg/common/common.go, apiserver/pkg/common/common_filter.go, controllers/base/application_controller.go
/kind bug
fix: move category filed from annotations to labels
Fixes #
=> fix: move category filed from annotations to labels

controllers/base/application_controller.go
/kind bug
fix: application loses recommended labels
Fixes #
=> fix: application loses recommended labels

apiserver/pkg/forwardrepo/modelscope_test.go
/kind bug
fix: remove modelscope test
Fixes #
=> fix: remove modelscope test

apiserver/docs/docs.go, apiserver/docs/swagger.json, apiserver/docs/swagger.yaml, apiserver/pkg/application/application.go, apiserver/pkg/chat/chat_server.go, apiserver/pkg/common/common.go, apiserver/pkg/gpt/gpt.go, apiserver/service/minio_server.go
/kind refactor
chore: add api to return image stream
Fixes #
=> chore: add api to return image stream

apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/schema/knowledgebase.gql, apiserver/graph/schema/knowledgebase.graphqls, apiserver/pkg/knowledgebase/knowledgebase.go
/kind feature
Add the latestVersion field of `KnowledgeBase.FileDetails`
Fixes #
=> feat: add the latestVersion field of `KnowledgeBase.FileDetails`

deploy/charts/arcadia/templates/role-templates.yaml
/kind bug
fix: role-teamplate is missing deletecolleciton permission
Fix https://github.com/kubeagi/ops-console/issues/321
=> fix: role-teamplate is missing deletecolleciton permission

apiserver/graph/impl/model.resolvers.go, apiserver/pkg/application/application.go, apiserver/pkg/chat/chat_docs.go, apiserver/pkg/common/common.go, apiserver/pkg/knowledgebase/knowledgebase.go, apiserver/pkg/model/model.go, apiserver/pkg/rag/rag.go, apiserver/pkg/rag/report.go, apiserver/pkg/versioneddataset/versioned_dataset.go, apiserver/service/minio_server.go, apiserver/service/rag_server.go, pkg/config/config.go, pkg/evaluation/jobs.go
=> fix: get system datasource oss and embedding suite from pkgconfig

deploy/charts/arcadia/templates/role-templates.yaml
=> fix: should user lowercase in role tempalte for multiqueryretrievers

apiserver/graph/generated/generated.go, apiserver/graph/generated/models_gen.go, apiserver/graph/schema/versioned_dataset.gql, apiserver/graph/schema/versioned_dataset.graphqls, apiserver/pkg/versioneddataset/versioned_dataset.go
feature
Add latestVersion field of `VersionedDataset.files`
Fixes #
=> feat: add latestVersion field of `VersionedDataset.files`

pkg/worker/worker.go
=> chore: avoid to update persistent volume claim 

deploy/charts/arcadia/templates/agent-portal.yaml
/kind cleanup
chore: remove some ingress configurations of agentportal
Fixes #
=> chore: remove some ingress configurations of agentportal

deploy/llama-factory/Chart.yaml, deploy/llama-factory/README.md, deploy/llama-factory/templates/deployment.yaml, deploy/llama-factory/templates/ingress.yaml, deploy/llama-factory/templates/service.yaml, deploy/llama-factory/values.yaml, deploy/llms/Dockerfile.fastchat-server
=> feat: add llama-factory chart

deploy/charts/arcadia/Chart.yaml, deploy/charts/arcadia/values.yaml
=> chore: add new hostname for host mapping

pkg/worker/worker.go
=> fix: worker check should add ns

apiserver/docs/docs.go, apiserver/docs/swagger.json, apiserver/docs/swagger.yaml, apiserver/service/chat.go, apiserver/service/forward.go
/kind bug
chore: swagger syntax error
Fixes #
=> chore: swagger syntax error
