kubeagi/arcadia

api/v1alpha1/condition.go
controllers/llm_controller.go

feat: add LLM controller

---

go.mod
go.sum
pkg/vectorstores/chromadb/chroma.go
pkg/vectorstores/chromadb/doc.go
pkg/vectorstores/chromadb/local_embedder.go
pkg/vectorstores/chromadb/options.go

feat: add chromadb

---

examples/chat_with_document/README.md
examples/chat_with_document/handler.go
examples/chat_with_document/start.go
go.mod

feat: add SSE invoke support for API server sample

---

.github/workflows/lint_test.yaml

For fix:
```
INFO: Downloading bootstrap version 'v2.0.0' of cosign to verify version to be installed...
https://storage.googleapis.com/cosign-releases/v2.0.0/cosign-linux-amd64
ERROR: Unable to validate cosign version: 'v2.0.0'
Error: Process completed with exit code 1.
```
upstream issue https://github.com/helm/chart-testing-action/issues/132

chore: bump helm/chart-testing-action version

---

tests/kind-config.yaml

If we use 1.24.13, in wsl and latest kind (v0.20.0), may have error
Fixes #

chore: bump k8s cluster version from 1.24.13 to 1.24.15

---

api/v1alpha1/knowledgebase.go
api/v1alpha1/knowledgebase_types.go
controllers/knowledgebase_controller.go

/kind feature
```yaml
apiVersion: arcadia.kubeagi.k8s.com.cn/v1alpha1
kind: KnowledgeBase
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"arcadia.kubeagi.k8s.com.cn/v1alpha1","kind":"KnowledgeBase","metadata":{"annotations":{},"name":"knowledgebase-sample","namespace":"arcadia"},"spec":{"description":"测试 KnowledgeBase","displayName":"测试 KnowledgeBase","embedder":{"kind":"Embedders","name":"zhipuai-embedders-sample","namespace":"arcadia"},"fileGroups":[{"paths":["dataset/dataset-playground/v1/qa.csv","dataset/dataset-playground/v1/qa1.csv"],"source":{"kind":"VersionedDataset","name":"dataset-playground-v1","namespace":"arcadia"}}],"vectorStore":{"kind":"VectorStores","name":"chroma-sample","namespace":"arcadia"}}}
creationTimestamp: …
```

feat: show skip handle file in knowledgebase status

---

config/samples/arcadia_v1alpha1_knowledgebase.yaml
controllers/knowledgebase_controller.go

/kind bug
Make the meaning and content of the field `path` in CRD `Knowledgebase` consistent with 
CRD `Versioneddataset` to avoid ambiguity
Fixes #

fix: knowledgebase.spec.fileGroups[*].path use path in versioneddataset

---

graphql-server/go-server/pkg/minio/client.go
pkg/llms/openai/api.go

/kind bug
fix: config minio secure and skip https authentication
Fixes #

fix: config minio secure and skip https authentication

---

graphql-server/go-server/graph/generated/generated.go
graphql-server/go-server/graph/generated/models_gen.go
graphql-server/go-server/graph/impl/worker.resolvers.go
graphql-server/go-server/graph/schema/datasource.gql
graphql-server/go-server/graph/schema/datasource.graphqls
graphql-server/go-server/graph/schema/entrypoint.graphqls
graphql-server/go-server/graph/schema/knowledgebase.gql
graphql-server/go-server/graph/schema/knowledgebase.graphqls
graphql-server/go-server/graph/schema/worker.gql
graphql-server/go-server/graph/schema/worker.graphqls
graphql-server/go-server/pkg/common/common.go
graphql-server/go-server/pkg/common/endpoint.go
graphql-server/go-server/pkg/common/schema.go
graphql-server/go-server/pkg/dataset/dataset.go
graphql-server/go-server/pkg/datasource/datasource.go
graphql-server/go-server/pkg/embedder/embedder.go
graphql-server/go-server/pkg/knowledgebase/knowledgebase.go
graphql-server/go-server/pkg/oidc/oidc.go
graphql-server/go-server/pkg/worker/worker.go
pkg/arctl/datasource.go

Signed-off-by: bjwswang <bjwswang@gmail.com>
Changelogs:
1. Add auth input in endpoint input
2. Make create/update auth secret a common function
3. add some missing fields in graphql server
Fixes #

fix: create and update auth secret for endpoint in graphql server

---

api/base/v1alpha1/embedder.go
api/base/v1alpha1/embedder_types.go
api/base/v1alpha1/worker.go
controllers/embedder_controller.go
controllers/knowledgebase_controller.go
controllers/model_controller.go
controllers/namespace_controller.go
controllers/versioneddataset_controller.go
controllers/worker_controller.go
graphql-server/go-server/pkg/embedder/embedder.go
main.go
pkg/application/app_run.go
pkg/application/chain/retrievalqachain.go
pkg/application/retriever/knowledgebaseretriever.go
pkg/config/config.go
pkg/embeddings/embeddings.go
pkg/scheduler/scheduler.go
pkg/utils/structured.go
pkg/worker/runner.go
tests/example-test.sh

/kind bug
1. Refactore some redundant functions
2. Use map to control exactly when each file is successfully embedding once (previously used the state of the cr to determine if it was processed, but there was a time lag between updating the state of the cr and getting the state of the cr, and the controller has a cache)
3. Use extended `StuffDocuments` to precisely control the format of the content given to LLM
4. Added many logs
```bash
Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.
q: 旷工最小计算单位为多少天？
a: "旷工最小计算单位为 0.5 天。"
q: 什么是旷工？
a: "旷工指未请假或请假未批准而擅自不上班或离岗者，不服从调动和工作分配，未按时到岗报到者；请假期限已满未续假或续假未批准而逾期不归者；有证据证明请假原因不属实、伪造或骗取请假、休假证件者；未按离职规定程序履行离职申请、审批，经要求仍拒不履行离职规定程序而擅自离岗者；因打架、斗殴致伤而不能 …
```

fix: get more accurate emberder segmentation

---

tests/example-test.sh

/kind cleanup
Recently we found that the example test often timeout failure (not 100%), research found that it is the dataprocess pod in the repeated failure to restart, we do not have dataprocess related tests in the example test, therefore, first to disable it to start.
For #365

chore: disable dataprocess pod in example-test

---

apiserver/pkg/application/application.go
apiserver/pkg/utils/structured.go

/kind bug
The front-end will sometimes give us an empty string value instead of null, and this pr is used to handle that case.
Fixes #

fix: when no knowledgebase setting or is empty, we should ignore it

---

.github/workflows/worker_image_build.yml
.github/workflows/worker_image_build_test.yml
deploy/llms/Dockerfile.fastchat-server
deploy/llms/Dockerfile.fastchat-worker
deploy/llms/Dockerfile.fastchat-worker-vllm
pkg/worker/runner.go

chore: update worker's dockerfile and use github action to build images

---

controllers/common.go
controllers/vectorstore_controller.go

/kind bug
Fixes #
<table>
<tr>
<td> user manal
<td> CR spec update
<td> CR status update
<td> CR metadata.generation update
<td> CR metadata.resourceVersion update
<td> CR deletionTimestamp update
<tr>
<td> spec A -> B
<td> spec.A -> spec.B 
<td> no change
<td> metadata.generation +1
<td> resourceVersion update
<td>
<tr>
<td>
<td> no change
<td> status.A -> status.B
<td> no change
<td> resourceVersion update
<td>
<tr>
<td>
<td> no change
<td> status.B -> status.B1(time update)
<td> no change
<td> resourceVersion update
<td>
<tr>
<td>
<td> no change
<td> status.B1 -> status.Bx(time update)
<td> no change
<td> resourceVersion update
<td>
<tr>
<td>
<td> 
<td> 
<td> 
<td>
<td>
<tr>
<td> delete CR
<td> no change
<td> no change
<td> metadata.generation +1
<td> resourceVersion update
<td> …

fix: vectorstore retry too quickly

---

apiserver/graph/generated/generated.go
apiserver/graph/generated/models_gen.go
apiserver/graph/impl/dataprocessing.resolvers.go
apiserver/graph/schema/dataprocessing.gql
apiserver/graph/schema/dataprocessing.graphqls
apiserver/pkg/dataprocessing/dataprocessing.go
data-processing/data_manipulation/common/const.py
data-processing/data_manipulation/controller/data_process_controller.py
data-processing/data_manipulation/data_store_process/minio_store_process.py
data-processing/data_manipulation/database_operate/data_process_db_operate.py
data-processing/data_manipulation/database_operate/data_process_detail_db_operate.py
data-processing/data_manipulation/database_operate/data_process_detail_preview_db_operate.py
data-processing/data_manipulation/database_operate/data_process_document_db_operate.py
data-processing/data_manipulation/llm_api_service/qa_provider_open_ai.py
data-processing/data_manipulation/llm_api_service/qa_provider_zhi_pu_ai_online.py
data-processing/data_manipulation/server.py
data-processing/data_manipulation/service/data_process_service.py
data-processing/db-scripts/init-database-schema.sql
deploy/charts/arcadia/templates/pg-init-data-configmap.yaml
gqlgen.yaml

/kind feature
/kind fix
Check for existing names during creation.
When deleting tasks, remove associated data.
fix: Randomly display 10 entries when previewing details.
fix: The number of processed files in details.
Fixes #

feat:check for existing names during creation.

---

.github/workflows/example_test.yaml

/kind cleanup
Fixes #
（Permission is required, I guess reviewer all have it)
1. Click 1 to manually run the github action
2. Click 2 to select the details
3. Click 3 to select which branch to run in 
4. Click 4 to select whether to only test the gql-sdk build without pushing the npm package (by default, ✅ is checked here, means only test) 
5. Click 5 to run 
6. Click 6 to get the results of the run
example for manually run: https://github.com/Abirdcfly/arcadia/actions/runs/7422789197/job/20198954330
example for pull request: https://github.com/Abirdcfly/arcadia/actions/runs/7422830827/job/20199075750?pr=4 
example for merge pull request: https://github.com/Abirdcfly/arcadia/actions/runs/7422835388/job/20199474323

fix: generate sdk for merge pull request

---

apiserver/docs/docs.go
apiserver/docs/swagger.json
apiserver/docs/swagger.yaml
apiserver/service/minio_server.go

/kind feature
feat: add api support to return to the download link
Fix https://github.com/kubeagi/arcadia/issues/534

Add api support to return to the download link

---

apiserver/pkg/versioneddataset/versioned_dataset.go

…version
bug
Fix the failure that create a Versioneddataset with the inherited historical version.
Fixes #

fix: Failed to create Versioneddataset with the inherited historical version

---

apiserver/graph/generated/generated.go
apiserver/graph/generated/models_gen.go
apiserver/graph/impl/dataprocessing.resolvers.go
apiserver/graph/schema/dataprocessing.gql
apiserver/graph/schema/dataprocessing.graphqls
apiserver/pkg/dataprocessing/dataprocessing.go
data-processing/data_manipulation/common/log_tag_const.py
data-processing/data_manipulation/common/special_characters.py
data-processing/data_manipulation/controller/data_process_controller.py
data-processing/data_manipulation/data_store_process/minio_store_process.py
data-processing/data_manipulation/database_operate/data_process_db_operate.py
data-processing/data_manipulation/database_operate/data_process_detail_db_operate.py
data-processing/data_manipulation/database_operate/data_process_document_chunk_db_operate.py
data-processing/data_manipulation/database_operate/data_process_document_db_operate.py
data-processing/data_manipulation/database_operate/data_process_log_db_operate.py
data-processing/data_manipulation/database_operate/data_process_stage_log_db_operate.py
data-processing/data_manipulation/file_handle/common_handle.py
data-processing/data_manipulation/file_handle/pdf_handle.py
data-processing/data_manipulation/file_handle/word_handle.py
data-processing/data_manipulation/service/data_process_service.py
data-processing/data_manipulation/transform/text/clean_transform.py
data-processing/db-scripts/init-database-schema.sql
deploy/charts/arcadia/templates/pg-init-data-configmap.yaml
gqlgen.yaml

/kind bug
/kind feature
feat: dataprocessing task retry functionality.
fix: After the model service is deleted, check the data processing tasks that previously used this service to see if they have failed.
fix: Processing of the DOCX file failed.
Fixes #487

feat:add dataprocessing task retry functionality

---

api/base/v1alpha1/datasource.go
api/base/v1alpha1/embedder.go
api/base/v1alpha1/llm.go
api/base/v1alpha1/model.go
apiserver/graph/generated/generated.go
apiserver/graph/generated/models_gen.go
apiserver/graph/schema/entrypoint.graphqls
apiserver/pkg/common/common.go
apiserver/pkg/knowledgebase/knowledgebase.go
controllers/base/datasource_controller.go
controllers/base/embedder_controller.go
controllers/base/llm_controller.go
controllers/base/model_controller.go
pkg/llms/llms.go

/kind fix 
Fixes #
Changelogs:
1. update resource status with explicitly status check
2. add displayName in graphql TypedObjectReference

fix: avoid to update resource status with explictly status check

---

apiserver/pkg/knowledgebase/knowledgebase.go
controllers/base/application_controller.go
pkg/appruntime/agent/executor.go
pkg/appruntime/agent/streamhandler.go
pkg/appruntime/app_runtime.go
pkg/appruntime/chain/llmchain.go
pkg/appruntime/prompt/prompt.go

1. support streaming of agent
2. allow chain behind agent

feat: support streaming and chain of agent

---

pkg/arctl/eval.go

/kind feature
support downloading files to specific directories
Fixes #
```shell
./arctl -nrag-eval eval download —rag=test123 —application=def —dir=/tmp/xyz
copy source /rag-eval/a.csv to /tmp/xyz/a.csv
copy source /rag-eval/kaoqin.csv to/tmp/xyz/kaoqin.csv
root@ecs-4fc018ff-1ded-4c65-92dc-67dc1911226c:/tmp/xyz$ ls
a.csv  kaoqin.csv
root@ecs-4fc018ff-1ded-4c65-92dc-67dc1911226c:/tmp/xyz$ cat a.csv
a,a
b,b
c,c
d,d
e,e
f,f
g,g
```

feat:support downloading files to specific directories

---

api/evaluation/v1alpha1/common.go
config/rbac/role.yaml
controllers/evaluation/rag_controller.go
deploy/charts/arcadia/Chart.yaml
deploy/charts/arcadia/templates/rbac.yaml
main.go
pkg/evaluation/jobs.go

/kind feature
feat: add rag controller
Fix https://github.com/kubeagi/arcadia/issues/566
The overall implementation logic is
First create the `pvc` and then create 4 stage jobs at a time.
The phase changes of rag are `""`, `"init"`, `"download"`, `"generate"`, `"judge"`, `"upload"`, `"complete"` at a time. You can tell if a phase is complete by `type=complete and status=true` in condition.
The rag will be suspend, the current stage of the job will be stopped, has been completed will not be processed. rag recovery, the current stage of the job will be re-created to continue execution of the pod, so the need for each stage to ensure that they can support the recovery of the suspend operation, to avoid suspend, after the recovery, the job can not be executed normally.
If the `data source` of …

[WIP]feat: add rag controller

---

apiserver/pkg/chat/chat_server.go
pkg/appruntime/chain/apichain.go
pkg/appruntime/chain/common.go
pkg/appruntime/chain/llmchain.go
pkg/appruntime/chain/retrievalqachain.go

When using **stream** mode and an error occurs, **fastchat** returns http code 200 and returns an error message in json, but this json is inconsistent with the default format of openai, so it is silently **ignored** by langchaingo, so in this case, we need to re-request the blocking mode to find the correct error message.
fastchat will return like this:
```
data: {"id": "chatcmpl-3Lo28HviQo8949WkJyfFzJ", "model": "7597c2a3-b186-4bac-b2e4-21ff56413f7f", "choices": [{"index": 0, "delta": {"role": "assistant"}, "finish_reason": null}]}
data: {"text": "**NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.**\n\n(\"addmm_impl_cpu_\" not implemented for 'Half')", "error_code": 50001}
data: [DONE]
```
/kind bug
Fixes #

fix: handle some errors in chat when using stream mode

---

controllers/base/knowledgebase_controller.go
main.go

/kind feature
Details:
- Added watch on Embedder and VectorStore resources for KnowledgeBase reconciliation.
- Updated the SetupWithManager function to include these watches.
- Modified the reconcile function to handle the case when Embedder or VectorStore is not ready.
- Added a condition to check for the readiness of Embedder and VectorStore before marking the KnowledgeBase as ready.
- Added error conditions for cases when Embedder or VectorStore is not ready.
This commit ensures that the KnowledgeBase is properly reconciled when its dependent resources, Embedder and VectorStore, are modified. It also improves the accuracy of the KnowledgeBase's ready status by taking into account the readiness of its dependencies.
when embedder is not ready, knowlegebase should also not ready...
Fixes …

feat: added watch on Embedder and VectorStore for KnowledgeBase reconciliation

---

Makefile
apiserver/docs/docs.go
apiserver/docs/swagger.json
apiserver/docs/swagger.yaml
apiserver/main.go
apiserver/pkg/chat/storage/storage_memory.go
apiserver/pkg/chat/storage/storage_postgresql.go
apiserver/service/chat.go
apiserver/service/minio_server.go

/kind feature
Previously listConversation API return the list of current user's sessions under a certain application, now there is a requirement in gpts to get the list of all the current user's sessions (by default sorted by time, with the newest conversations at the top), and all that is needed is for the application parameter of the listconversation API to be made optional. 
In the local 40 environment test passed.
by the way, add `swag fmt` for swagger comment.
Fixes #

feat: return users all conversation

---

deploy/charts/arcadia/Chart.yaml
deploy/charts/arcadia/templates/rag_job_rbac.yaml

/kind bug
Find the permissions needed for the command gen_test_dataset
Fixes #

fix:find the permissions needed for the command gen_test_dataset

---

config/rbac/role.yaml
controllers/evaluation/rag_controller.go
deploy/charts/arcadia/Chart.yaml
deploy/charts/arcadia/templates/rbac.yaml

/kind bug
fix: apiserver needs access to storageclass
Fixes #

fix: apiserver needs access to storageclass

---

apiserver/pkg/chat/chat_server.go
pkg/appruntime/app_runtime.go
pkg/appruntime/base/node.go
pkg/appruntime/retriever/knowledgebaseretriever.go
pkg/evaluation/evaluation.go

/kind cleanup
This commit introduces a `Cleanup()` function to the `Node` interface in the `pkg/appruntime/base` package. This function allows nodes to perform cleanup operations when they are finished executing.
Currently the main use is to release the connection to pg, by manually releasing the connection it solves a lot of shenanigans like chat timeout with no content, gpts list 504, etc. (gpts hits are also recorded in pg)
By the way, removing a lot of redundant `base.SetAppNamespace` calls.
Fixes #

fix(appruntime): Add `Cleanup()` function to Node interface

---

api/base/v1alpha1/condition.go
config/rbac/role.yaml
controllers/base/application_controller.go
deploy/charts/arcadia/templates/rbac.yaml
main.go
pkg/appruntime/app_runtime.go
pkg/appruntime/base/node.go
pkg/appruntime/chain/apichain.go
pkg/appruntime/chain/llmchain.go
pkg/appruntime/chain/retrievalqachain.go
pkg/appruntime/knowledgebase/knowledgebase.go
pkg/appruntime/llm/llm.go
pkg/appruntime/prompt/prompt.go
pkg/appruntime/retriever/knowledgebaseretriever.go

/kind feature
This commit adds `Ready` methods to all nodes in the application.
These methods provide a consistent way to check if a node is ready and to get any error messages that may have occurred during node initialization or execution.
The following changes were made to implement this feature:
- Added `Ready` methods to the `Node` interface.
- Implemented `Ready` methods for all existing node types.
- Updated the application controller to use the `Ready` methods to check if nodes are ready and to handle any errors that may occur.
Fixes #
based on #696, need merge that first.

fix(application): add isReady check for all nodes in application

---

deploy/charts/arcadia/Chart.yaml
deploy/charts/arcadia/values.yaml

feat: release v0.2.0

---

api/base/v1alpha1/model_types.go
config/crd/bases/arcadia.kubeagi.k8s.com.cn_models.yaml
controllers/base/model_controller.go
deploy/charts/arcadia/crds/arcadia.kubeagi.k8s.com.cn_models.yaml
deploy/llms/Dockerfile.fastchat-worker
pkg/worker/loader.go
pkg/worker/runner.go
pkg/worker/worker.go

/kind feature
chore: upgrade fastchat to v0.2.36
For #781

chore: support downloading files from the model repository

---

api/base/v1alpha1/worker.go
config/samples/arcadia_v1alpha1_worker_reranking.yaml
pkg/worker/runner.go
pkg/worker/worker.go

/kind feat
Fixes #
We have a our own runner(implemented by https://github.com/kubeagi/core-library/pull/25) at core-libary
Has been tested with `BCEReranking` ,but for `BGEReranking` a error occured https://github.com/kubeagi/core-library/issues/33

feat(worker): add RunnerKubeAGI to host reranking models

---

.github/workflows/example_test.yaml
controllers/base/llm_controller.go
pkg/appruntime/app_runtime.go
pkg/appruntime/log/log.go
tests/example-test.sh

/kind flake
1. Trigger a fast reconcile by returning an error when the state of the llm is not ready, instead of waiting 1 hour for a reconcile as if the state of the llm was ready.
2.  Use different apikey in 3 tests at the same time, used to reduce the level of concurrency.
3.  3 retries after chat error
Fixes #
In testing, there are still 2 relatively rare error cases (excluding errors returned by the LLM itself) that need to be fixed with subsequent pull requests
1. apiserver panic just log `2024-03-08T06:18:53.745667941Z stderr F 2024/03/08 06:18:53 googleapi: Error 503:`
3. `{"error":"run node chain-node: llmchain run error: Post \"https://generativelanguage.googleapis.com/v1/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint\u0026key=xxxxxxx\": context deadline …

fix: make gemini fail more less

---

pypi/data-processing/src/common/config.py
pypi/data-processing/src/document_chunks/spacy_text_splitter.py
pypi/data-processing/src/kube/model_cr.py
pypi/data-processing/src/server.py

Retrieve chunkSize and worker from the configmap.

feat:Retrieve chunkSize and worker from the configmap.

---

apiserver/graph/generated/generated.go
apiserver/graph/generated/models_gen.go
apiserver/graph/schema/dataprocessing.gql
apiserver/graph/schema/dataprocessing.graphqls
deploy/charts/arcadia/templates/pg-init-data-configmap.yaml
pypi/data-processing/db-scripts/change/20240319-schema.sql
pypi/data-processing/requirements.txt
pypi/data-processing/src/database_operate/data_process_db_operate.py
pypi/data-processing/src/service/data_process_service.py

the time consumed for data processing.
#913 
#761

feat:the time consumed for data processing.

---

api/base/v1alpha1/condition.go
apiserver/graph/generated/generated.go
apiserver/graph/generated/models_gen.go
apiserver/graph/schema/gpt.gql
apiserver/graph/schema/gpt.graphqls
apiserver/pkg/auth/auth.go
apiserver/pkg/gpt/gpt.go
apiserver/service/gpts.go
apiserver/service/router.go
controllers/base/application_controller.go
controllers/base/knowledgebase_controller.go
pkg/appruntime/app_runtime.go

/kind bug
/kind feature
1. add showRespInfo / showRetrievalInfo / showNextGuide /  enableUploadFile / notReadyReasonCode to gpts
2. add /gpts/chat api for gpts, which only check user token is valid
For #933 
@zggmd front web ui also need update.

feat: add gpts chat api

---

.github/workflows/example_test.yaml
api/base/v1alpha1/application.go
api/base/v1alpha1/application_types.go
apiserver/graph/generated/generated.go
apiserver/graph/generated/models_gen.go
apiserver/graph/schema/application.gql
apiserver/graph/schema/application.graphqls
apiserver/graph/schema/datasource.gql
apiserver/graph/schema/gpt.gql
apiserver/graph/schema/gpt.graphqls
apiserver/pkg/application/application.go
config/crd/bases/arcadia.kubeagi.k8s.com.cn_applications.yaml
controllers/base/application_controller.go
controllers/base/datasource_controller.go
controllers/base/embedder_controller.go
controllers/base/model_controller.go
controllers/base/prompt_controller.go
deploy/charts/arcadia/Chart.yaml
deploy/charts/arcadia/README.md
deploy/charts/arcadia/crds/arcadia.kubeagi.k8s.com.cn_applications.yaml
deploy/charts/arcadia/templates/agent-portal.yaml
deploy/charts/arcadia/templates/config.yaml
deploy/charts/arcadia/values.yaml
pkg/config/gpts_config.go
tests/deploy-values.yaml

Fixes #946 
Fixeds #940 
1. add public namespace for gpts
2. add label to indicate app is recommended
3. make sure error is returned after status update
4. reduce action pallel  to 1(fails too often if 3)

feat: able to configure public namespace for gpts

---

apiserver/graph/generated/generated.go
apiserver/graph/generated/models_gen.go
apiserver/graph/schema/application.gql
apiserver/graph/schema/application.graphqls
apiserver/pkg/application/application.go

feat: export systemPrompt in gql

---

api/base/v1alpha1/worker.go
apiserver/pkg/application/application.go
apiserver/pkg/knowledgebase/knowledgebase.go
apiserver/pkg/versioneddataset/versioned_dataset.go
apiserver/pkg/worker/worker.go
deploy/charts/arcadia/templates/rag-rbac.yaml
pkg/versioneddataset/versioneddataset.go

/kind fix
Fixes #978 
The reason to make sure all typed reference have  `apigroup`,`namespace` set due to below error:
```shell
Error: node llm-node init failed: can't convert to langchain llm: an empty namespace may not be set when a resource name is provided
Usage:
arctl eval gen_test_dataset [flags]
Flags:
--ground-truths-column string   The column name which provides the answers (default "a")
-h, --help                          help for gen_test_dataset
--input-dir string              The input directory where to load original dataset files
--max-context-length int        The maximum length of the context (default 512)
--merge                         Whether to merge all generated test data into a single file
--merge-file string             name of the merged document (default …
```

Couple fixes for RAG evaluation

---

deploy/charts/arcadia/templates/role-templates.yaml

feat: add role templates for kubeagi

---

Dockerfile
apiserver/pkg/application/application.go
apiserver/pkg/chat/chat_docs.go
apiserver/pkg/chat/chat_server.go
apiserver/pkg/common/common.go
apiserver/pkg/gpt/gpt.go
apiserver/pkg/knowledgebase/knowledgebase.go
apiserver/pkg/ray/raycluster.go
apiserver/service/chat.go
apiserver/service/gpts.go
apiserver/service/router.go
controllers/app-node/retriever/rerank_retriever_controller.go
controllers/base/knowledgebase_controller.go
controllers/base/model_controller.go
controllers/base/namespace_controller.go
controllers/base/versioneddataset_controller.go
controllers/base/worker_controller.go
controllers/evaluation/rag_controller.go
deploy/charts/arcadia/templates/role-templates.yaml
main.go
pkg/appruntime/documentloader/documentloader.go
pkg/arctl/eval.go
pkg/config/config.go
pkg/evaluation/jobs.go
pkg/langchainwrap/embedder.go
pkg/langchainwrap/llm.go
pkg/scheduler/scheduler.go
pkg/streamlit/deployer.go
pkg/worker/runner.go

fix: use system client to get config

---

apiserver/service/chat.go
apiserver/service/minio_server.go
apiserver/service/rag_server.go

fix: get username in chat

---

apiserver/graph/generated/generated.go
apiserver/graph/generated/models_gen.go
apiserver/graph/schema/application.gql
apiserver/graph/schema/application.graphqls
apiserver/graph/schema/gpt.graphqls
apiserver/pkg/application/application.go

/kind bug
/kind feature
1. Add notReadyReasonCode to app
2. fix cant set batchsize

feat: add notReadyReasonCode into app

---

pypi/data-processing/src/data_store_process/minio_store_process.py
pypi/data-processing/src/database_operate/data_process_document_db_operate.py
pypi/data-processing/src/file_handle/common_handle.py
pypi/data-processing/src/service/data_process_qa_remove_duplicate.py
pypi/data-processing/src/service/data_process_service.py

vectorize in batches.
Fixes #915

fix:vectorize in batches.

---

apiserver/pkg/chat/chat_docs.go
apiserver/pkg/chat/chat_server.go

fix: common user can only access public app

---

apiserver/pkg/chat/chat_server.go

fix: use system client to list&delete knowledgebase for conversation

---

pkg/langchainwrap/debug_transport.go
pkg/langchainwrap/llm.go

/kind feature
Fixes #
log example:
```log
I0410 07:06:48.141884       1 app_runtime.go:197] "try to run node:prompt-node" requestID="d857dcdb2ef313009c8a65aa3481b7ff"
I0410 07:06:48.141897       1 app_runtime.go:197] "try to run node:chain-node" requestID="d857dcdb2ef313009c8a65aa3481b7ff"
I0410 07:06:48.142083       1 log.go:53] "Entering LLM with messages: text: Human: \nnihRole: human" requestID="d857dcdb2ef313009c8a65aa3481b7ff"
I0410 07:06:48.142302       1 debug_transport.go:26] "POST /v1/chat/completions HTTP/1.1\r\nHost: arcadia-fastchat.kubeagi-system.svc.cluster.local:8000\r\nUser-Agent: Go-http-client/1.1\r\nContent-Length: 153\r\nAuthorization: Bearer fake\r\nContent-Type: application/json\r\nAccept-Encoding: gzip\r\n\r\n{\"model\":\"chatglm_lite\",\"messages\":[{\"role\":\"use …
```

feat: add http debug client for llm call

---

README.md
deploy/charts/arcadia/Chart.yaml
deploy/charts/arcadia/values.yaml

release v0.2.2
